/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/calebwin/Projects/pipelines/pipelines/nimcache/pipelines_pipelines.o /home/calebwin/Projects/pipelines/pipelines/nimcache/pipelines_pipelines.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ;
typedef struct tySequence_6j25whH7XTBoIXcM0x1T7A tySequence_6j25whH7XTBoIXcM0x1T7A;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_7XI1p02ImfLQezfcEUv8og tySequence_7XI1p02ImfLQezfcEUv8og;
typedef struct tyTuple_CpHT6GSYxsDkQccg9cjxyeQ tyTuple_CpHT6GSYxsDkQccg9cjxyeQ;
typedef struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg tyTuple_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct tyTuple_9cdgeqdY7FRioNKBoD6G66A tyTuple_9cdgeqdY7FRioNKBoD6G66A;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ {
tySequence_6j25whH7XTBoIXcM0x1T7A* data;
NI counter;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
typedef NU8 tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ;
struct tyTuple_CpHT6GSYxsDkQccg9cjxyeQ {
NimStringDesc* Field0;
tyTuple_7q7q3E6Oj24ZNVJb9aonhAg Field1;
NimStringDesc* Field2;
tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ Field3;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg {
NI a;
NI b;
};
struct tyTuple_9cdgeqdY7FRioNKBoD6G66A {
NI Field0;
NimStringDesc* Field1;
tyTuple_UV3llMMYFckfui8YMBuUZA Field2;
};
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING path);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(NI, tyProc_grsFbooLsFDKsgZemLk4tA) (NCSTRING str);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_7XI1p02ImfLQezfcEUv8og {
  TGenericSeq Sup;
  tyTuple_CpHT6GSYxsDkQccg9cjxyeQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_6j25whH7XTBoIXcM0x1T7A {
  TGenericSeq Sup;
  tyTuple_9cdgeqdY7FRioNKBoD6G66A data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, main_q9bSBSJj3hQHzQv8K8KDJ9aQ)(void);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_NIMCALL(void, runFile_X3niW4GrgIHr9b1EZWxUoDw)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, compile_ZpQvIaozpQbtVMgryZrHaQ)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
N_NIMCALL(void, initTable_ULT5Nh6n23CMlrIkYDrA0w)(NI initialSize, tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_7XI1p02ImfLQezfcEUv8og)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NIM_BOOL, nsuIsNilOrWhitespace)(NimStringDesc* s);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQpipelines)(void* a, void* b, NI size);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswpipelines)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYApipelines)(NI a, NI b);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars, NI start, NI last);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(void, X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t, NimStringDesc* key, tyTuple_UV3llMMYFckfui8YMBuUZA val);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(NIM_BOOL, substrEq_7ngl0F5lryTkSAj7sYQ7pw)(NimStringDesc* s, NI pos, NimStringDesc* substr);
N_NIMCALL(void, nsuRemoveSuffixString)(NimStringDesc** s, NimStringDesc* suffix);
N_NIMCALL(NimStringDesc*, nsuIndent)(NimStringDesc* s, NI count, NimStringDesc* padding);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(void, compileFile_X3niW4GrgIHr9b1EZWxUoDw_2)(NimStringDesc* path);
N_NIMCALL(void, writeFile_c1B29b0ZdDRPHc27YaKqwaA)(NimStringDesc* filename, NimStringDesc* content);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, pipelinesDatInit000)(void);
TNimType NTI_UV3llMMYFckfui8YMBuUZA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_CpHT6GSYxsDkQccg9cjxyeQ_;
TNimType NTI_7q7q3E6Oj24ZNVJb9aonhAg_;
TNimType NTI_E4jA5qxWxmTFyMwtKBqcRQ_;
TNimType NTI_7XI1p02ImfLQezfcEUv8og_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125184_;
extern tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_125822_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_125943_;
extern tyProc_grsFbooLsFDKsgZemLk4tA Dl_125255_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125923_;
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_2, "Welcome to Pipelines!", 21);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_3, "v:0.1.0", 7);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_10, "", 0);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_11, "(", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_12, "#", 1);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_ffc2zNBeCfY9caiwpQV67xw_13 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_ffc2zNBeCfY9caiwpQV67xw_14 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_15, "import", 6);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_16, "|>", 2);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_17, "/>", 2);
NIM_CONST tyTuple_7q7q3E6Oj24ZNVJb9aonhAg TM_ffc2zNBeCfY9caiwpQV67xw_18 = {((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10),
((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10),
((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10)}
;
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_19, "where", 5);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_20, "to", 2);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_21, "with", 4);
NIM_CONST tyTuple_7q7q3E6Oj24ZNVJb9aonhAg TM_ffc2zNBeCfY9caiwpQV67xw_22 = {((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10),
((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10),
((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10)}
;
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_23, "from multiprocessing import Process, Queue\012", 43);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_24, "from ", 5);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_25, " import ", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_26, " as ", 4);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_27, "\012", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_28, "class PLPipeSentinel: pass\012", 27);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_29, "def pl_run_", 11);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_30, "(pl_stream, pl_out_queue):\012", 27);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_31, "\011for pl_data in pl_stream:\012", 27);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_32, "\011\011pl_out_queue.put(pl_data)\012", 28);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_33, "\011pl_out_queue.put(PLPipeSentinel())\012", 36);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_34, "*", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_35, "pl_inp", 6);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_36, "(pl_inp)", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_37, ")", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_38, ",", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_39, " = None\012", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_40, "while 1:\012", 9);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_41, "\011pl_inp = pl_in_queue.get()\012", 28);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_42, "\011", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_43, " = pl_inp\012", 10);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_44, "\011if isinstance(pl_inp, PLPipeSentinel):\012", 40);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_45, "\011\011pl_outp = PLPipeSentinel()\012", 29);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_46, "\011if not isinstance(pl_inp, PLPipeSentinel):\012", 44);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_47, "\011\011pl_outp = ", 12);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_48, "\011\011", 2);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_49, " = pl_outp\012", 11);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_50, "\011\011pl_result = ", 14);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_51, " = pl_result\012", 13);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_52, "\011\011if ", 5);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_53, ":\012", 2);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_54, "\011\011if pl_result:\012", 16);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_55, "\011\011\011pl_outp = pl_inp\012", 20);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_56, "\011\011else:\012", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_57, "\011\011\011continue\012", 12);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_58, "\011if pl_out_queue is not None:\012", 30);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_59, "\011\011pl_out_queue.put(pl_outp)\012", 28);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_60, "\011\011break\012", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_61, "(pl_in_queue, pl_out_queue):\012", 29);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_62, "pl_data = ", 10);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_63, "()\012", 3);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_64, "pl_in_", 6);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_65, " = Queue()\012", 11);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_66, "pl_", 3);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_67, "_process = Process(target=pl_run_", 33);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_68, ", args=(pl_data, pl_in_", 23);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_69, "))\012", 3);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_70, "None", 4);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_71, ", args=(", 8);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_72, ",))\012", 4);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_73, "_process.start()\012", 17);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_74, "_process.join()\012", 16);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_75, "if __name__ == \"__main__\":\012", 27);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_76, ":", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_77, "/", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_78, "r", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_79, "run", 3);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_80, "c", 1);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_81, "compile", 7);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_82, ".pipeline", 9);
STRING_LITERAL(TM_ffc2zNBeCfY9caiwpQV67xw_83, ".py", 3);
static N_NIMCALL(void, Marker_tySequence_7XI1p02ImfLQezfcEUv8og)(void* p, NI op) {
	tySequence_7XI1p02ImfLQezfcEUv8og* a;
	NI T1_;
	a = (tySequence_7XI1p02ImfLQezfcEUv8og*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1.Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1.Field1, op);
	nimGCvisit((void*)a->data[T1_].Field1.Field2, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQpipelines)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQpipelines(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswpipelines)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	result = (NimStringDesc*)0;
	result = copyStrLast(s, x.a, x.b);
	return result;
}

static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYApipelines)(NI a, NI b) {
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}

N_NIMCALL(NimStringDesc*, compile_ZpQvIaozpQbtVMgryZrHaQ)(NimStringDesc* path) {
	NimStringDesc* result;
	NimStringDesc* contents;
	tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ paths;
	tySequence_7XI1p02ImfLQezfcEUv8og* pipes;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* tokens;
	NimStringDesc* token;
	NI index;
	NI tokenIndex;
	NimStringDesc* code;
	NimStringDesc* mainCode;
	NimStringDesc* generatorName;
	NimStringDesc* T167_;
	NI componentIndex;
	NimStringDesc* iteratorModule;
	NimStringDesc* T242_;
	NimStringDesc* T248_;
	NI pipeIndex;
	NimStringDesc* T262_;
	NimStringDesc* T273_;
	NimStringDesc* T274_;
	result = (NimStringDesc*)0;
	contents = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(path);
	memset((void*)(&paths), 0, sizeof(paths));
	chckNil((void*)(&paths));
	memset((void*)(&paths), 0, sizeof(paths));
	initTable_ULT5Nh6n23CMlrIkYDrA0w(((NI) 64), (&paths));
	pipes = (tySequence_7XI1p02ImfLQezfcEUv8og*) newSeq((&NTI_7XI1p02ImfLQezfcEUv8og_), 0);
	tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	token = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
	index = ((NI) 0);
	{
		while (1) {
			NimStringDesc* character;
			if (!(index <= (NI)((contents ? contents->Sup.len : 0) - ((NI) 1)))) goto LA2;
			character = nimCharToStr(contents->data[index]);
			{
				NIM_BOOL T5_;
				NIM_BOOL T6_;
				T5_ = (NIM_BOOL)0;
				T6_ = (NIM_BOOL)0;
				T6_ = nsuIsNilOrWhitespace(character);
				if (T6_) goto LA7_;
				T6_ = eqStrings(character, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11));
				LA7_: ;
				T5_ = T6_;
				if (T5_) goto LA8_;
				T5_ = eqStrings(character, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_12));
				LA8_: ;
				if (!T5_) goto LA9_;
				{
					NimStringDesc* T13_;
					NimStringDesc* T16_;
					NI T17_;
					NimStringDesc* T18_;
					T13_ = (NimStringDesc*)0;
					T13_ = nsuStrip(token, NIM_TRUE, NIM_TRUE, TM_ffc2zNBeCfY9caiwpQV67xw_13);
					if (!(((NI) 0) < (T13_ ? T13_->Sup.len : 0))) goto LA14_;
					T16_ = (NimStringDesc*)0;
					T16_ = nsuStrip(token, NIM_TRUE, NIM_TRUE, TM_ffc2zNBeCfY9caiwpQV67xw_13);
					tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(tokens)->Sup, sizeof(NimStringDesc*));
					T17_ = tokens->Sup.len++;
					T18_ = (NimStringDesc*)0;
					T18_ = tokens->data[T17_]; tokens->data[T17_] = copyStringRC1(T16_);
					if (T18_) nimGCunrefNoCycle(T18_);
				}
				LA14_: ;
				token = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
			}
			LA9_: ;
			{
				NimStringDesc* parameterDeclaration;
				NI T23_;
				tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T24_;
				NI T25_;
				NimStringDesc* T26_;
				NI T27_;
				if (!eqStrings(character, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11))) goto LA21_;
				T23_ = (NI)0;
				T23_ = nsuFindChar(contents, 41, ((NI) (index)), ((NI) 0));
				T24_ = dotdot__18yoMoUbfoITYgEZSwZDYApipelines(index, T23_);
				parameterDeclaration = X5BX5D__Sq9b57KCLKZryBwyHy49aBswpipelines(contents, T24_);
				tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(tokens)->Sup, sizeof(NimStringDesc*));
				T25_ = tokens->Sup.len++;
				T26_ = (NimStringDesc*)0;
				T26_ = tokens->data[T25_]; tokens->data[T25_] = copyStringRC1(parameterDeclaration);
				if (T26_) nimGCunrefNoCycle(T26_);
				T27_ = (NI)0;
				T27_ = nsuFindChar(contents, 41, ((NI) (index)), ((NI) 0));
				index = (NI)(T27_ + ((NI) 1));
			}
			goto LA19_;
			LA21_: ;
			{
				NI T31_;
				if (!eqStrings(character, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_12))) goto LA29_;
				T31_ = (NI)0;
				T31_ = nsuFindCharSet(contents, TM_ffc2zNBeCfY9caiwpQV67xw_14, ((NI) (index)), ((NI) 0));
				index = (NI)(T31_ + ((NI) 1));
			}
			goto LA19_;
			LA29_: ;
			{
				token = resizeString(token, character->Sup.len + 0);
appendString(token, character);
				index += ((NI) 1);
			}
			LA19_: ;
		} LA2: ;
	}
	tokenIndex = ((NI) 0);
	{
		NimStringDesc* token_2;
		NI i;
		NI L;
		NI T34_;
		token_2 = (NimStringDesc*)0;
		i = ((NI) 0);
		T34_ = (tokens ? tokens->Sup.len : 0);
		L = T34_;
		{
			while (1) {
				if (!(i < L)) goto LA36;
				token_2 = tokens->data[i];
				if (eqStrings(token_2, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_15))) goto LA37_;
				if (eqStrings(token_2, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_16))) goto LA38_;
				if (eqStrings(token_2, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_17))) goto LA39_;
				goto LA40_;
				LA37_: ;
				{
					NimStringDesc* newPathAlias;
					NimStringDesc* newPathModule;
					NimStringDesc* newPathFunction;
					tyTuple_UV3llMMYFckfui8YMBuUZA newPath;
					newPathAlias = tokens->data[(NI)((NI)(tokenIndex + ((NI) 1)) + ((NI) 2))];
					newPathModule = tokens->data[(NI)(tokenIndex - ((NI) 1))];
					newPathFunction = tokens->data[(NI)(tokenIndex + ((NI) 1))];
					memset((void*)(&newPath), 0, sizeof(newPath));
					newPath.Field0 = copyString(newPathModule);
					newPath.Field1 = copyString(newPathFunction);
					X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA((&paths), newPathAlias, newPath);
				}
				goto LA41_;
				LA38_: ;
				{
					NimStringDesc* prevToken;
					NimStringDesc* nextToken;
					NimStringDesc* newPipeOrigin;
					NimStringDesc* newPipeDestination;
					NI numModifiers;
					tyTuple_7q7q3E6Oj24ZNVJb9aonhAg modifiers;
					tyTuple_CpHT6GSYxsDkQccg9cjxyeQ T92_;
					NI T93_;
					NimStringDesc* T94_;
					NimStringDesc* T95_;
					NimStringDesc* T96_;
					NimStringDesc* T97_;
					NimStringDesc* T98_;
					prevToken = tokens->data[(NI)(tokenIndex - ((NI) 1))];
					nextToken = tokens->data[(NI)(tokenIndex + ((NI) 1))];
					newPipeOrigin = prevToken;
					newPipeDestination = nextToken;
					numModifiers = ((NI) 0);
					memset((void*)(&modifiers), 0, sizeof(modifiers));
					modifiers.Field0 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_18.Field0);
					modifiers.Field1 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_18.Field1);
					modifiers.Field2 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_18.Field2);
					{
						NIM_BOOL T46_;
						NI T48_;
						T46_ = (NIM_BOOL)0;
						T46_ = (numModifiers == ((NI) 0));
						if (!(T46_)) goto LA47_;
						T48_ = (tokens ? tokens->Sup.len : 0);
						T46_ = ((NI)(tokenIndex + ((NI) 3)) <= (NI)(T48_ - ((NI) 1)));
						LA47_: ;
						if (!T46_) goto LA49_;
						numModifiers += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA51_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA52_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA53_;
						goto LA54_;
						LA51_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA55_;
						LA52_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA55_;
						LA53_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA55_;
						LA54_: ;
						{
						}
						LA55_: ;
					}
					LA49_: ;
					{
						NIM_BOOL T62_;
						NI T64_;
						T62_ = (NIM_BOOL)0;
						T62_ = (numModifiers == ((NI) 1));
						if (!(T62_)) goto LA63_;
						T64_ = (tokens ? tokens->Sup.len : 0);
						T62_ = ((NI)(tokenIndex + ((NI) 5)) <= (NI)(T64_ - ((NI) 1)));
						LA63_: ;
						if (!T62_) goto LA65_;
						numModifiers += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA67_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA68_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA69_;
						goto LA70_;
						LA67_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA71_;
						LA68_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA71_;
						LA69_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA71_;
						LA70_: ;
						{
						}
						LA71_: ;
					}
					LA65_: ;
					{
						NIM_BOOL T78_;
						NI T80_;
						T78_ = (NIM_BOOL)0;
						T78_ = (numModifiers == ((NI) 2));
						if (!(T78_)) goto LA79_;
						T80_ = (tokens ? tokens->Sup.len : 0);
						T78_ = ((NI)(tokenIndex + ((NI) 7)) <= (NI)(T80_ - ((NI) 1)));
						LA79_: ;
						if (!T78_) goto LA81_;
						numModifiers += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA83_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA84_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA85_;
						goto LA86_;
						LA83_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA87_;
						LA84_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA87_;
						LA85_: ;
						{
							unsureAsgnRef((void**) (&modifiers.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA87_;
						LA86_: ;
						{
						}
						LA87_: ;
					}
					LA81_: ;
					memset((void*)(&T92_), 0, sizeof(T92_));
					T92_.Field0 = copyString(newPipeOrigin);
					T92_.Field1.Field0 = copyString(modifiers.Field0);
					T92_.Field1.Field1 = copyString(modifiers.Field1);
					T92_.Field1.Field2 = copyString(modifiers.Field2);
					T92_.Field2 = copyString(newPipeDestination);
					T92_.Field3 = ((tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ) 0);
					pipes = (tySequence_7XI1p02ImfLQezfcEUv8og*) incrSeqV2(&(pipes)->Sup, sizeof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ));
					T93_ = pipes->Sup.len++;
					T94_ = (NimStringDesc*)0;
					T94_ = pipes->data[T93_].Field0; pipes->data[T93_].Field0 = copyStringRC1(T92_.Field0);
					if (T94_) nimGCunrefNoCycle(T94_);
					T95_ = (NimStringDesc*)0;
					T95_ = pipes->data[T93_].Field1.Field0; pipes->data[T93_].Field1.Field0 = copyStringRC1(T92_.Field1.Field0);
					if (T95_) nimGCunrefNoCycle(T95_);
					T96_ = (NimStringDesc*)0;
					T96_ = pipes->data[T93_].Field1.Field1; pipes->data[T93_].Field1.Field1 = copyStringRC1(T92_.Field1.Field1);
					if (T96_) nimGCunrefNoCycle(T96_);
					T97_ = (NimStringDesc*)0;
					T97_ = pipes->data[T93_].Field1.Field2; pipes->data[T93_].Field1.Field2 = copyStringRC1(T92_.Field1.Field2);
					if (T97_) nimGCunrefNoCycle(T97_);
					T98_ = (NimStringDesc*)0;
					T98_ = pipes->data[T93_].Field2; pipes->data[T93_].Field2 = copyStringRC1(T92_.Field2);
					if (T98_) nimGCunrefNoCycle(T98_);
					pipes->data[T93_].Field3 = T92_.Field3;
				}
				goto LA41_;
				LA39_: ;
				{
					NimStringDesc* prevToken_2;
					NimStringDesc* nextToken_2;
					NimStringDesc* newPipeOrigin_2;
					NimStringDesc* newPipeDestination_2;
					NI numModifiers_2;
					tyTuple_7q7q3E6Oj24ZNVJb9aonhAg modifiers_2;
					tyTuple_CpHT6GSYxsDkQccg9cjxyeQ T148_;
					NI T149_;
					NimStringDesc* T150_;
					NimStringDesc* T151_;
					NimStringDesc* T152_;
					NimStringDesc* T153_;
					NimStringDesc* T154_;
					prevToken_2 = tokens->data[(NI)(tokenIndex - ((NI) 1))];
					nextToken_2 = tokens->data[(NI)(tokenIndex + ((NI) 1))];
					newPipeOrigin_2 = prevToken_2;
					newPipeDestination_2 = nextToken_2;
					numModifiers_2 = ((NI) 0);
					memset((void*)(&modifiers_2), 0, sizeof(modifiers_2));
					modifiers_2.Field0 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_22.Field0);
					modifiers_2.Field1 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_22.Field1);
					modifiers_2.Field2 = copyString(TM_ffc2zNBeCfY9caiwpQV67xw_22.Field2);
					{
						NIM_BOOL T102_;
						NI T104_;
						T102_ = (NIM_BOOL)0;
						T102_ = (numModifiers_2 == ((NI) 0));
						if (!(T102_)) goto LA103_;
						T104_ = (tokens ? tokens->Sup.len : 0);
						T102_ = ((NI)(tokenIndex + ((NI) 3)) <= (NI)(T104_ - ((NI) 1)));
						LA103_: ;
						if (!T102_) goto LA105_;
						numModifiers_2 += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA107_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA108_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 2))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA109_;
						goto LA110_;
						LA107_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA111_;
						LA108_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA111_;
						LA109_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 3))]));
						}
						goto LA111_;
						LA110_: ;
						{
							numModifiers_2 -= ((NI) 1);
						}
						LA111_: ;
					}
					LA105_: ;
					{
						NIM_BOOL T118_;
						NI T120_;
						T118_ = (NIM_BOOL)0;
						T118_ = (numModifiers_2 == ((NI) 1));
						if (!(T118_)) goto LA119_;
						T120_ = (tokens ? tokens->Sup.len : 0);
						T118_ = ((NI)(tokenIndex + ((NI) 5)) <= (NI)(T120_ - ((NI) 1)));
						LA119_: ;
						if (!T118_) goto LA121_;
						numModifiers_2 += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA123_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA124_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 4))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA125_;
						goto LA126_;
						LA123_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA127_;
						LA124_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA127_;
						LA125_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 5))]));
						}
						goto LA127_;
						LA126_: ;
						{
							numModifiers_2 -= ((NI) 1);
						}
						LA127_: ;
					}
					LA121_: ;
					{
						NIM_BOOL T134_;
						NI T136_;
						T134_ = (NIM_BOOL)0;
						T134_ = (numModifiers_2 == ((NI) 2));
						if (!(T134_)) goto LA135_;
						T136_ = (tokens ? tokens->Sup.len : 0);
						T134_ = ((NI)(tokenIndex + ((NI) 7)) <= (NI)(T136_ - ((NI) 1)));
						LA135_: ;
						if (!T134_) goto LA137_;
						numModifiers_2 += ((NI) 1);
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_19))) goto LA139_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_20))) goto LA140_;
						if (eqStrings(tokens->data[(NI)(tokenIndex + ((NI) 6))], ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_21))) goto LA141_;
						goto LA142_;
						LA139_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field0), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA143_;
						LA140_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field1), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA143_;
						LA141_: ;
						{
							unsureAsgnRef((void**) (&modifiers_2.Field2), copyString(tokens->data[(NI)(tokenIndex + ((NI) 7))]));
						}
						goto LA143_;
						LA142_: ;
						{
							numModifiers_2 -= ((NI) 1);
						}
						LA143_: ;
					}
					LA137_: ;
					memset((void*)(&T148_), 0, sizeof(T148_));
					T148_.Field0 = copyString(newPipeOrigin_2);
					T148_.Field1.Field0 = copyString(modifiers_2.Field0);
					T148_.Field1.Field1 = copyString(modifiers_2.Field1);
					T148_.Field1.Field2 = copyString(modifiers_2.Field2);
					T148_.Field2 = copyString(newPipeDestination_2);
					T148_.Field3 = ((tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ) 1);
					pipes = (tySequence_7XI1p02ImfLQezfcEUv8og*) incrSeqV2(&(pipes)->Sup, sizeof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ));
					T149_ = pipes->Sup.len++;
					T150_ = (NimStringDesc*)0;
					T150_ = pipes->data[T149_].Field0; pipes->data[T149_].Field0 = copyStringRC1(T148_.Field0);
					if (T150_) nimGCunrefNoCycle(T150_);
					T151_ = (NimStringDesc*)0;
					T151_ = pipes->data[T149_].Field1.Field0; pipes->data[T149_].Field1.Field0 = copyStringRC1(T148_.Field1.Field0);
					if (T151_) nimGCunrefNoCycle(T151_);
					T152_ = (NimStringDesc*)0;
					T152_ = pipes->data[T149_].Field1.Field1; pipes->data[T149_].Field1.Field1 = copyStringRC1(T148_.Field1.Field1);
					if (T152_) nimGCunrefNoCycle(T152_);
					T153_ = (NimStringDesc*)0;
					T153_ = pipes->data[T149_].Field1.Field2; pipes->data[T149_].Field1.Field2 = copyStringRC1(T148_.Field1.Field2);
					if (T153_) nimGCunrefNoCycle(T153_);
					T154_ = (NimStringDesc*)0;
					T154_ = pipes->data[T149_].Field2; pipes->data[T149_].Field2 = copyStringRC1(T148_.Field2);
					if (T154_) nimGCunrefNoCycle(T154_);
					pipes->data[T149_].Field3 = T148_.Field3;
				}
				goto LA41_;
				LA40_: ;
				{
				}
				LA41_: ;
				tokenIndex += ((NI) 1);
				i += ((NI) 1);
			} LA36: ;
		}
	}
	code = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_23));
	mainCode = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
	{
		NimStringDesc* alias;
		tyTuple_UV3llMMYFckfui8YMBuUZA path_2;
		alias = (NimStringDesc*)0;
		memset((void*)(&path_2), 0, sizeof(path_2));
		{
			NI h;
			NI colontmp_;
			NI T158_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			T158_ = (paths.data ? (paths.data->Sup.len-1) : -1);
			colontmp_ = T158_;
			res = ((NI) 0);
			{
				while (1) {
					if (!(res <= colontmp_)) goto LA160;
					h = res;
					{
						NIM_BOOL T163_;
						NimStringDesc* T166_;
						T163_ = (NIM_BOOL)0;
						T163_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(paths.data->data[h].Field0);
						if (!T163_) goto LA164_;
						alias = paths.data->data[h].Field1;
						path_2.Field0 = paths.data->data[h].Field2.Field0;
						path_2.Field1 = paths.data->data[h].Field2.Field1;
						T166_ = (NimStringDesc*)0;
						T166_ = rawNewString(path_2.Field0->Sup.len + path_2.Field1->Sup.len + alias->Sup.len + 18);
appendString(T166_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_24));
appendString(T166_, path_2.Field0);
appendString(T166_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_25));
appendString(T166_, path_2.Field1);
appendString(T166_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_26));
appendString(T166_, alias);
appendString(T166_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
						code = resizeString(code, T166_->Sup.len + 0);
appendString(code, T166_);
					}
					LA164_: ;
					res += ((NI) 1);
				} LA160: ;
			}
		}
	}
	code = resizeString(code, 27);
appendString(code, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_28));
	generatorName = pipes->data[((NI) 0)].Field0;
	T167_ = (NimStringDesc*)0;
	T167_ = rawNewString(generatorName->Sup.len + 38);
appendString(T167_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_29));
appendString(T167_, generatorName);
appendString(T167_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_30));
	code = resizeString(code, T167_->Sup.len + 0);
appendString(code, T167_);
	code = resizeString(code, 27);
appendString(code, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_31));
	code = resizeString(code, 28);
appendString(code, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_32));
	code = resizeString(code, 36);
appendString(code, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_33));
	componentIndex = ((NI) 0);
	{
		tyTuple_CpHT6GSYxsDkQccg9cjxyeQ pipe;
		NI i_2;
		NI L_2;
		NI T169_;
		memset((void*)(&pipe), 0, sizeof(pipe));
		i_2 = ((NI) 0);
		T169_ = (pipes ? pipes->Sup.len : 0);
		L_2 = T169_;
		{
			while (1) {
				NimStringDesc* component;
				tyTuple_7q7q3E6Oj24ZNVJb9aonhAg modifiers_3;
				NimStringDesc* parameters;
				NimStringDesc* inputs;
				NimStringDesc* componentCode;
				NimStringDesc* T239_;
				NimStringDesc* T240_;
				NimStringDesc* T241_;
				if (!(i_2 < L_2)) goto LA171;
				pipe.Field0 = pipes->data[i_2].Field0;
				pipe.Field1.Field0 = pipes->data[i_2].Field1.Field0;
				pipe.Field1.Field1 = pipes->data[i_2].Field1.Field1;
				pipe.Field1.Field2 = pipes->data[i_2].Field1.Field2;
				pipe.Field2 = pipes->data[i_2].Field2;
				pipe.Field3 = pipes->data[i_2].Field3;
				component = pipe.Field2;
				memset((void*)(&modifiers_3), 0, sizeof(modifiers_3));
				modifiers_3.Field0 = pipe.Field1.Field0;
				modifiers_3.Field1 = pipe.Field1.Field1;
				modifiers_3.Field2 = pipe.Field1.Field2;
				{
					if (!(((NI) 0) < (modifiers_3.Field0 ? modifiers_3.Field0->Sup.len : 0))) goto LA174_;
					parameters = nsuReplaceStr(modifiers_3.Field0, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_34), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_35));
				}
				goto LA172_;
				LA174_: ;
				{
					parameters = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_36));
				}
				LA172_: ;
				{
					NimStringDesc* T181_;
					if (!(((NI) 0) < componentIndex)) goto LA179_;
					T181_ = (NimStringDesc*)0;
					T181_ = nsuReplaceStr(pipes->data[(NI)(componentIndex - ((NI) 1))].Field1.Field1, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
					inputs = nsuReplaceStr(T181_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_37), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
				}
				goto LA177_;
				LA179_: ;
				{
					inputs = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
				}
				LA177_: ;
				componentCode = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
				{
					NimStringDesc* to;
					NimStringDesc* colontmp__2;
					NimStringDesc* T184_;
					NI last;
					NI splits;
					to = (NimStringDesc*)0;
					colontmp__2 = (NimStringDesc*)0;
					T184_ = (NimStringDesc*)0;
					T184_ = nsuReplaceStr(modifiers_3.Field1, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
					colontmp__2 = nsuReplaceStr(T184_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_37), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
					last = ((NI) 0);
					splits = ((NI) -1);
					{
						if (!(((NI) 0) < (colontmp__2 ? colontmp__2->Sup.len : 0))) goto LA187_;
						{
							while (1) {
								NI first;
								NimStringDesc* T200_;
								NimStringDesc* T201_;
								if (!(last <= (colontmp__2 ? colontmp__2->Sup.len : 0))) goto LA190;
								first = last;
								{
									while (1) {
										NIM_BOOL T193_;
										NIM_BOOL T195_;
										T193_ = (NIM_BOOL)0;
										T193_ = (last < (colontmp__2 ? colontmp__2->Sup.len : 0));
										if (!(T193_)) goto LA194_;
										T195_ = (NIM_BOOL)0;
										T195_ = substrEq_7ngl0F5lryTkSAj7sYQ7pw(colontmp__2, last, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_38));
										T193_ = !(T195_);
										LA194_: ;
										if (!T193_) goto LA192;
										last += ((NI) 1);
									} LA192: ;
								}
								{
									if (!(splits == ((NI) 0))) goto LA198_;
									last = (colontmp__2 ? colontmp__2->Sup.len : 0);
								}
								LA198_: ;
								to = copyStrLast(colontmp__2, first, (NI)(last - ((NI) 1)));
								T200_ = (NimStringDesc*)0;
								T201_ = (NimStringDesc*)0;
								T201_ = nsuStrip(to, NIM_TRUE, NIM_TRUE, TM_ffc2zNBeCfY9caiwpQV67xw_13);
								T200_ = rawNewString(T201_->Sup.len + 8);
appendString(T200_, T201_);
appendString(T200_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_39));
								componentCode = resizeString(componentCode, T200_->Sup.len + 0);
appendString(componentCode, T200_);
								{
									if (!(splits == ((NI) 0))) goto LA204_;
									goto LA189;
								}
								LA204_: ;
								splits -= ((NI) 1);
								last += ((NI) 1);
							} LA190: ;
						} LA189: ;
					}
					LA187_: ;
				}
				componentCode = resizeString(componentCode, 9);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_40));
				componentCode = resizeString(componentCode, 28);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_41));
				{
					NIM_BOOL T208_;
					NimStringDesc* T212_;
					T208_ = (NIM_BOOL)0;
					T208_ = !(((inputs) && (inputs)->Sup.len == 0));
					if (!(T208_)) goto LA209_;
					T208_ = (pipes->data[(NI)(componentIndex - ((NI) 1))].Field3 == ((tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ) 0));
					LA209_: ;
					if (!T208_) goto LA210_;
					T212_ = (NimStringDesc*)0;
					T212_ = rawNewString(inputs->Sup.len + 11);
appendString(T212_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_42));
appendString(T212_, inputs);
appendString(T212_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_43));
					componentCode = resizeString(componentCode, T212_->Sup.len + 0);
appendString(componentCode, T212_);
				}
				LA210_: ;
				componentCode = resizeString(componentCode, 40);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_44));
				componentCode = resizeString(componentCode, 29);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_45));
				switch (pipe.Field3) {
				case ((tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ) 0):
				{
					NimStringDesc* T214_;
					componentCode = resizeString(componentCode, 44);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_46));
					T214_ = (NimStringDesc*)0;
					T214_ = rawNewString(component->Sup.len + parameters->Sup.len + 13);
appendString(T214_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_47));
appendString(T214_, component);
appendString(T214_, parameters);
appendString(T214_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
					componentCode = resizeString(componentCode, T214_->Sup.len + 0);
appendString(componentCode, T214_);
					{
						NimStringDesc* T219_;
						NimStringDesc* T220_;
						NimStringDesc* T221_;
						if (!(((NI) 0) < (modifiers_3.Field1 ? modifiers_3.Field1->Sup.len : 0))) goto LA217_;
						T219_ = (NimStringDesc*)0;
						T220_ = (NimStringDesc*)0;
						T220_ = nsuReplaceStr(modifiers_3.Field1, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T221_ = (NimStringDesc*)0;
						T221_ = nsuReplaceStr(T220_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_37), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T219_ = rawNewString(T221_->Sup.len + 13);
appendString(T219_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_48));
appendString(T219_, T221_);
appendString(T219_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_49));
						componentCode = resizeString(componentCode, T219_->Sup.len + 0);
appendString(componentCode, T219_);
					}
					LA217_: ;
				}
				break;
				case ((tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ) 1):
				{
					NimStringDesc* T223_;
					componentCode = resizeString(componentCode, 44);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_46));
					T223_ = (NimStringDesc*)0;
					T223_ = rawNewString(component->Sup.len + parameters->Sup.len + 15);
appendString(T223_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_50));
appendString(T223_, component);
appendString(T223_, parameters);
appendString(T223_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
					componentCode = resizeString(componentCode, T223_->Sup.len + 0);
appendString(componentCode, T223_);
					{
						NimStringDesc* T228_;
						NimStringDesc* T229_;
						NimStringDesc* T230_;
						if (!(((NI) 0) < (modifiers_3.Field1 ? modifiers_3.Field1->Sup.len : 0))) goto LA226_;
						T228_ = (NimStringDesc*)0;
						T229_ = (NimStringDesc*)0;
						T229_ = nsuReplaceStr(modifiers_3.Field1, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T230_ = (NimStringDesc*)0;
						T230_ = nsuReplaceStr(T229_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_37), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T228_ = rawNewString(T230_->Sup.len + 15);
appendString(T228_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_48));
appendString(T228_, T230_);
appendString(T228_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_51));
						componentCode = resizeString(componentCode, T228_->Sup.len + 0);
appendString(componentCode, T228_);
					}
					LA226_: ;
					{
						NimStringDesc* T235_;
						NimStringDesc* T236_;
						NimStringDesc* T237_;
						if (!(((NI) 0) < (modifiers_3.Field2 ? modifiers_3.Field2->Sup.len : 0))) goto LA233_;
						T235_ = (NimStringDesc*)0;
						T236_ = (NimStringDesc*)0;
						T236_ = nsuReplaceStr(modifiers_3.Field2, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_11), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T237_ = (NimStringDesc*)0;
						T237_ = nsuReplaceStr(T236_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_37), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_10));
						T235_ = rawNewString(T237_->Sup.len + 7);
appendString(T235_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_52));
appendString(T235_, T237_);
appendString(T235_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_53));
						componentCode = resizeString(componentCode, T235_->Sup.len + 0);
appendString(componentCode, T235_);
					}
					goto LA231_;
					LA233_: ;
					{
						componentCode = resizeString(componentCode, 16);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_54));
					}
					LA231_: ;
					componentCode = resizeString(componentCode, 20);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_55));
					componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_56));
					componentCode = resizeString(componentCode, 12);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_57));
				}
				break;
				}
				componentCode = resizeString(componentCode, 30);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_58));
				componentCode = resizeString(componentCode, 28);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_59));
				componentCode = resizeString(componentCode, 40);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_44));
				componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_60));
				componentIndex += ((NI) 1);
				T239_ = (NimStringDesc*)0;
				T239_ = rawNewString(component->Sup.len + 40);
appendString(T239_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_29));
appendString(T239_, component);
appendString(T239_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_61));
				code = resizeString(code, T239_->Sup.len + 0);
appendString(code, T239_);
				nsuRemoveSuffixString((&componentCode), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
				T240_ = (NimStringDesc*)0;
				T241_ = (NimStringDesc*)0;
				T241_ = nsuIndent(componentCode, ((NI) 1), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_42));
				T240_ = rawNewString(T241_->Sup.len + 1);
appendString(T240_, T241_);
appendString(T240_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
				code = resizeString(code, T240_->Sup.len + 0);
appendString(code, T240_);
				i_2 += ((NI) 1);
			} LA171: ;
		}
	}
	iteratorModule = pipes->data[((NI) 0)].Field0;
	T242_ = (NimStringDesc*)0;
	T242_ = rawNewString(iteratorModule->Sup.len + 13);
appendString(T242_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_62));
appendString(T242_, iteratorModule);
appendString(T242_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_63));
	mainCode = resizeString(mainCode, T242_->Sup.len + 0);
appendString(mainCode, T242_);
	{
		tyTuple_CpHT6GSYxsDkQccg9cjxyeQ pipe_2;
		NI i_3;
		NI L_3;
		NI T244_;
		memset((void*)(&pipe_2), 0, sizeof(pipe_2));
		i_3 = ((NI) 0);
		T244_ = (pipes ? pipes->Sup.len : 0);
		L_3 = T244_;
		{
			while (1) {
				NimStringDesc* component_2;
				NimStringDesc* T247_;
				if (!(i_3 < L_3)) goto LA246;
				pipe_2.Field0 = pipes->data[i_3].Field0;
				pipe_2.Field1.Field0 = pipes->data[i_3].Field1.Field0;
				pipe_2.Field1.Field1 = pipes->data[i_3].Field1.Field1;
				pipe_2.Field1.Field2 = pipes->data[i_3].Field1.Field2;
				pipe_2.Field2 = pipes->data[i_3].Field2;
				pipe_2.Field3 = pipes->data[i_3].Field3;
				component_2 = pipe_2.Field2;
				T247_ = (NimStringDesc*)0;
				T247_ = rawNewString(component_2->Sup.len + 17);
appendString(T247_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_64));
appendString(T247_, component_2);
appendString(T247_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_65));
				mainCode = resizeString(mainCode, T247_->Sup.len + 0);
appendString(mainCode, T247_);
				i_3 += ((NI) 1);
			} LA246: ;
		}
	}
	T248_ = (NimStringDesc*)0;
	T248_ = rawNewString(generatorName->Sup.len + generatorName->Sup.len + pipes->data[((NI) 0)].Field2->Sup.len + 62);
appendString(T248_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_66));
appendString(T248_, generatorName);
appendString(T248_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_67));
appendString(T248_, generatorName);
appendString(T248_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_68));
appendString(T248_, pipes->data[((NI) 0)].Field2);
appendString(T248_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_69));
	mainCode = resizeString(mainCode, T248_->Sup.len + 0);
appendString(mainCode, T248_);
	pipeIndex = ((NI) 0);
	{
		tyTuple_CpHT6GSYxsDkQccg9cjxyeQ pipe_3;
		NI i_4;
		NI L_4;
		NI T250_;
		memset((void*)(&pipe_3), 0, sizeof(pipe_3));
		i_4 = ((NI) 0);
		T250_ = (pipes ? pipes->Sup.len : 0);
		L_4 = T250_;
		{
			while (1) {
				NimStringDesc* component_3;
				NimStringDesc* componentQueue;
				NimStringDesc* T253_;
				NimStringDesc* nextComponentQueue;
				NimStringDesc* T261_;
				if (!(i_4 < L_4)) goto LA252;
				pipe_3.Field0 = pipes->data[i_4].Field0;
				pipe_3.Field1.Field0 = pipes->data[i_4].Field1.Field0;
				pipe_3.Field1.Field1 = pipes->data[i_4].Field1.Field1;
				pipe_3.Field1.Field2 = pipes->data[i_4].Field1.Field2;
				pipe_3.Field2 = pipes->data[i_4].Field2;
				pipe_3.Field3 = pipes->data[i_4].Field3;
				component_3 = pipes->data[pipeIndex].Field2;
				T253_ = (NimStringDesc*)0;
				T253_ = rawNewString(component_3->Sup.len + 6);
appendString(T253_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_64));
appendString(T253_, component_3);
				componentQueue = T253_;
				{
					NI T256_;
					NimStringDesc* T259_;
					T256_ = (pipes ? pipes->Sup.len : 0);
					if (!(pipeIndex < (NI)(T256_ - ((NI) 1)))) goto LA257_;
					T259_ = (NimStringDesc*)0;
					T259_ = rawNewString(pipes->data[(NI)(pipeIndex + ((NI) 1))].Field2->Sup.len + 6);
appendString(T259_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_64));
appendString(T259_, pipes->data[(NI)(pipeIndex + ((NI) 1))].Field2);
					nextComponentQueue = T259_;
				}
				goto LA254_;
				LA257_: ;
				{
					nextComponentQueue = copyString(((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_70));
				}
				LA254_: ;
				T261_ = (NimStringDesc*)0;
				T261_ = rawNewString(component_3->Sup.len + component_3->Sup.len + componentQueue->Sup.len + nextComponentQueue->Sup.len + 49);
appendString(T261_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_66));
appendString(T261_, component_3);
appendString(T261_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_67));
appendString(T261_, component_3);
appendString(T261_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_71));
appendString(T261_, componentQueue);
appendString(T261_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_38));
appendString(T261_, nextComponentQueue);
appendString(T261_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_72));
				mainCode = resizeString(mainCode, T261_->Sup.len + 0);
appendString(mainCode, T261_);
				pipeIndex += ((NI) 1);
				i_4 += ((NI) 1);
			} LA252: ;
		}
	}
	T262_ = (NimStringDesc*)0;
	T262_ = rawNewString(generatorName->Sup.len + 20);
appendString(T262_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_66));
appendString(T262_, generatorName);
appendString(T262_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_73));
	mainCode = resizeString(mainCode, T262_->Sup.len + 0);
appendString(mainCode, T262_);
	{
		tyTuple_CpHT6GSYxsDkQccg9cjxyeQ pipe_4;
		NI i_5;
		NI L_5;
		NI T264_;
		memset((void*)(&pipe_4), 0, sizeof(pipe_4));
		i_5 = ((NI) 0);
		T264_ = (pipes ? pipes->Sup.len : 0);
		L_5 = T264_;
		{
			while (1) {
				NimStringDesc* component_4;
				NimStringDesc* T267_;
				if (!(i_5 < L_5)) goto LA266;
				pipe_4.Field0 = pipes->data[i_5].Field0;
				pipe_4.Field1.Field0 = pipes->data[i_5].Field1.Field0;
				pipe_4.Field1.Field1 = pipes->data[i_5].Field1.Field1;
				pipe_4.Field1.Field2 = pipes->data[i_5].Field1.Field2;
				pipe_4.Field2 = pipes->data[i_5].Field2;
				pipe_4.Field3 = pipes->data[i_5].Field3;
				component_4 = pipe_4.Field2;
				T267_ = (NimStringDesc*)0;
				T267_ = rawNewString(component_4->Sup.len + 20);
appendString(T267_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_66));
appendString(T267_, component_4);
appendString(T267_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_73));
				mainCode = resizeString(mainCode, T267_->Sup.len + 0);
appendString(mainCode, T267_);
				i_5 += ((NI) 1);
			} LA266: ;
		}
	}
	{
		tyTuple_CpHT6GSYxsDkQccg9cjxyeQ pipe_5;
		NI i_6;
		NI L_6;
		NI T269_;
		memset((void*)(&pipe_5), 0, sizeof(pipe_5));
		i_6 = ((NI) 0);
		T269_ = (pipes ? pipes->Sup.len : 0);
		L_6 = T269_;
		{
			while (1) {
				NimStringDesc* component_5;
				NimStringDesc* T272_;
				if (!(i_6 < L_6)) goto LA271;
				pipe_5.Field0 = pipes->data[i_6].Field0;
				pipe_5.Field1.Field0 = pipes->data[i_6].Field1.Field0;
				pipe_5.Field1.Field1 = pipes->data[i_6].Field1.Field1;
				pipe_5.Field1.Field2 = pipes->data[i_6].Field1.Field2;
				pipe_5.Field2 = pipes->data[i_6].Field2;
				pipe_5.Field3 = pipes->data[i_6].Field3;
				component_5 = pipe_5.Field2;
				T272_ = (NimStringDesc*)0;
				T272_ = rawNewString(component_5->Sup.len + 19);
appendString(T272_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_66));
appendString(T272_, component_5);
appendString(T272_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_74));
				mainCode = resizeString(mainCode, T272_->Sup.len + 0);
appendString(mainCode, T272_);
				i_6 += ((NI) 1);
			} LA271: ;
		}
	}
	code = resizeString(code, 27);
appendString(code, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_75));
	nsuRemoveSuffixString((&mainCode), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
	T273_ = (NimStringDesc*)0;
	T274_ = (NimStringDesc*)0;
	T274_ = nsuIndent(mainCode, ((NI) 1), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_42));
	T273_ = rawNewString(T274_->Sup.len + 1);
appendString(T273_, T274_);
appendString(T273_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_27));
	code = resizeString(code, T273_->Sup.len + 0);
appendString(code, T273_);
	result = copyString(code);
	{
		if (!NIM_TRUE) goto LA277_;
		printf("%s\012", code? (code)->data:"nil");
		fflush(stdout);
	}
	LA277_: ;
	return result;
}

N_NIMCALL(void, runFile_X3niW4GrgIHr9b1EZWxUoDw)(NimStringDesc* path) {
	NCSTRING code;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NCSTRING T3_;
	NimStringDesc* T4_;
	NI T5_;
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T6_;
	NimStringDesc* T7_;
	NI T8_;
	T1_ = (NimStringDesc*)0;
	T1_ = compile_ZpQvIaozpQbtVMgryZrHaQ(path);
	code = T1_->data;
	Dl_125184_();
	T2_ = (NimStringDesc*)0;
	T3_ = (NCSTRING)0;
	T3_ = Dl_125943_();
	T4_ = (NimStringDesc*)0;
	T4_ = cstrToNimstr(T3_);
	T5_ = (NI)0;
	T5_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(path, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_77), ((NI) -1));
	T6_ = dotdot__18yoMoUbfoITYgEZSwZDYApipelines(((NI) 0), T5_);
	T7_ = (NimStringDesc*)0;
	T7_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswpipelines(path, T6_);
	T2_ = rawNewString(T4_->Sup.len + T7_->Sup.len + 1);
appendString(T2_, T4_);
appendString(T2_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_76));
appendString(T2_, T7_);
	Dl_125822_(T2_->data);
	T8_ = (NI)0;
	T8_ = Dl_125255_(code);
	T8_;
	Dl_125923_();
}

N_NIMCALL(void, compileFile_X3niW4GrgIHr9b1EZWxUoDw_2)(NimStringDesc* path) {
	NimStringDesc* code;
	NimStringDesc* targetPath;
	code = compile_ZpQvIaozpQbtVMgryZrHaQ(path);
	targetPath = nsuReplaceStr(path, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_82), ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_83));
	writeFile_c1B29b0ZdDRPHc27YaKqwaA(targetPath, code);
}

N_NIMCALL(void, main_q9bSBSJj3hQHzQv8K8KDJ9aQ)(void) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = paramCount_T74rCHY8RMV0X07YnKmggw();
	switch (T1_) {
	case ((NI) 0):
	{
		printf("%s\012", ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_2)? (((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_2))->data:"nil");
		fflush(stdout);
		printf("%s\012", ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_3)? (((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_3))->data:"nil");
		fflush(stdout);
	}
	break;
	case ((NI) 1):
	{
		NimStringDesc* path;
		path = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		runFile_X3niW4GrgIHr9b1EZWxUoDw(path);
	}
	break;
	case ((NI) 2):
	{
		NimStringDesc* T5_;
		T5_ = (NimStringDesc*)0;
		T5_ = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		if (eqStrings(T5_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_78))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_79))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_80))) goto LA7_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_ffc2zNBeCfY9caiwpQV67xw_81))) goto LA7_;
		goto LA8_;
		LA6_: ;
		{
			NimStringDesc* path_2;
			path_2 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			runFile_X3niW4GrgIHr9b1EZWxUoDw(path_2);
		}
		goto LA9_;
		LA7_: ;
		{
			NimStringDesc* path_3;
			path_3 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			compileFile_X3niW4GrgIHr9b1EZWxUoDw_2(path_3);
		}
		goto LA9_;
		LA8_: ;
		{
		}
		LA9_: ;
	}
	break;
	default:
	{
	}
	break;
	}
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	python_pythonDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	pipelinesDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	python_pythonInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_sequtilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	main_q9bSBSJj3hQHzQv8K8KDJ9aQ();
}

NIM_EXTERNC N_NOINLINE(void, pipelinesDatInit000)(void) {
static TNimNode* TM_ffc2zNBeCfY9caiwpQV67xw_4[2];
static TNimNode* TM_ffc2zNBeCfY9caiwpQV67xw_5[4];
static TNimNode* TM_ffc2zNBeCfY9caiwpQV67xw_6[3];
static TNimNode* TM_ffc2zNBeCfY9caiwpQV67xw_7[2];
NI TM_ffc2zNBeCfY9caiwpQV67xw_9;
static char* NIM_CONST TM_ffc2zNBeCfY9caiwpQV67xw_8[2] = {
"pTransformer", 
"pFilter"};
static TNimNode TM_ffc2zNBeCfY9caiwpQV67xw_0[15];
NTI_UV3llMMYFckfui8YMBuUZA_.size = sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA);
NTI_UV3llMMYFckfui8YMBuUZA_.kind = 18;
NTI_UV3llMMYFckfui8YMBuUZA_.base = 0;
NTI_UV3llMMYFckfui8YMBuUZA_.flags = 2;
TM_ffc2zNBeCfY9caiwpQV67xw_4[0] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[1];
TM_ffc2zNBeCfY9caiwpQV67xw_0[1].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[1].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field0);
TM_ffc2zNBeCfY9caiwpQV67xw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[1].name = "Field0";
TM_ffc2zNBeCfY9caiwpQV67xw_4[1] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[2];
TM_ffc2zNBeCfY9caiwpQV67xw_0[2].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[2].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field1);
TM_ffc2zNBeCfY9caiwpQV67xw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[2].name = "Field1";
TM_ffc2zNBeCfY9caiwpQV67xw_0[0].len = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[0].kind = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[0].sons = &TM_ffc2zNBeCfY9caiwpQV67xw_4[0];
NTI_UV3llMMYFckfui8YMBuUZA_.node = &TM_ffc2zNBeCfY9caiwpQV67xw_0[0];
NTI_CpHT6GSYxsDkQccg9cjxyeQ_.size = sizeof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ);
NTI_CpHT6GSYxsDkQccg9cjxyeQ_.kind = 18;
NTI_CpHT6GSYxsDkQccg9cjxyeQ_.base = 0;
NTI_CpHT6GSYxsDkQccg9cjxyeQ_.flags = 2;
TM_ffc2zNBeCfY9caiwpQV67xw_5[0] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[4];
TM_ffc2zNBeCfY9caiwpQV67xw_0[4].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[4].offset = offsetof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ, Field0);
TM_ffc2zNBeCfY9caiwpQV67xw_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[4].name = "Field0";
TM_ffc2zNBeCfY9caiwpQV67xw_5[1] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[5];
NTI_7q7q3E6Oj24ZNVJb9aonhAg_.size = sizeof(tyTuple_7q7q3E6Oj24ZNVJb9aonhAg);
NTI_7q7q3E6Oj24ZNVJb9aonhAg_.kind = 18;
NTI_7q7q3E6Oj24ZNVJb9aonhAg_.base = 0;
NTI_7q7q3E6Oj24ZNVJb9aonhAg_.flags = 2;
TM_ffc2zNBeCfY9caiwpQV67xw_6[0] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[7];
TM_ffc2zNBeCfY9caiwpQV67xw_0[7].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[7].offset = offsetof(tyTuple_7q7q3E6Oj24ZNVJb9aonhAg, Field0);
TM_ffc2zNBeCfY9caiwpQV67xw_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[7].name = "Field0";
TM_ffc2zNBeCfY9caiwpQV67xw_6[1] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[8];
TM_ffc2zNBeCfY9caiwpQV67xw_0[8].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[8].offset = offsetof(tyTuple_7q7q3E6Oj24ZNVJb9aonhAg, Field1);
TM_ffc2zNBeCfY9caiwpQV67xw_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[8].name = "Field1";
TM_ffc2zNBeCfY9caiwpQV67xw_6[2] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[9];
TM_ffc2zNBeCfY9caiwpQV67xw_0[9].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[9].offset = offsetof(tyTuple_7q7q3E6Oj24ZNVJb9aonhAg, Field2);
TM_ffc2zNBeCfY9caiwpQV67xw_0[9].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[9].name = "Field2";
TM_ffc2zNBeCfY9caiwpQV67xw_0[6].len = 3; TM_ffc2zNBeCfY9caiwpQV67xw_0[6].kind = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[6].sons = &TM_ffc2zNBeCfY9caiwpQV67xw_6[0];
NTI_7q7q3E6Oj24ZNVJb9aonhAg_.node = &TM_ffc2zNBeCfY9caiwpQV67xw_0[6];
TM_ffc2zNBeCfY9caiwpQV67xw_0[5].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[5].offset = offsetof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ, Field1);
TM_ffc2zNBeCfY9caiwpQV67xw_0[5].typ = (&NTI_7q7q3E6Oj24ZNVJb9aonhAg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[5].name = "Field1";
TM_ffc2zNBeCfY9caiwpQV67xw_5[2] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[10];
TM_ffc2zNBeCfY9caiwpQV67xw_0[10].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[10].offset = offsetof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ, Field2);
TM_ffc2zNBeCfY9caiwpQV67xw_0[10].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[10].name = "Field2";
TM_ffc2zNBeCfY9caiwpQV67xw_5[3] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[11];
NTI_E4jA5qxWxmTFyMwtKBqcRQ_.size = sizeof(tyEnum_Pipes_E4jA5qxWxmTFyMwtKBqcRQ);
NTI_E4jA5qxWxmTFyMwtKBqcRQ_.kind = 14;
NTI_E4jA5qxWxmTFyMwtKBqcRQ_.base = 0;
NTI_E4jA5qxWxmTFyMwtKBqcRQ_.flags = 3;
for (TM_ffc2zNBeCfY9caiwpQV67xw_9 = 0; TM_ffc2zNBeCfY9caiwpQV67xw_9 < 2; TM_ffc2zNBeCfY9caiwpQV67xw_9++) {
TM_ffc2zNBeCfY9caiwpQV67xw_0[TM_ffc2zNBeCfY9caiwpQV67xw_9+12].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[TM_ffc2zNBeCfY9caiwpQV67xw_9+12].offset = TM_ffc2zNBeCfY9caiwpQV67xw_9;
TM_ffc2zNBeCfY9caiwpQV67xw_0[TM_ffc2zNBeCfY9caiwpQV67xw_9+12].name = TM_ffc2zNBeCfY9caiwpQV67xw_8[TM_ffc2zNBeCfY9caiwpQV67xw_9];
TM_ffc2zNBeCfY9caiwpQV67xw_7[TM_ffc2zNBeCfY9caiwpQV67xw_9] = &TM_ffc2zNBeCfY9caiwpQV67xw_0[TM_ffc2zNBeCfY9caiwpQV67xw_9+12];
}
TM_ffc2zNBeCfY9caiwpQV67xw_0[14].len = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[14].kind = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[14].sons = &TM_ffc2zNBeCfY9caiwpQV67xw_7[0];
NTI_E4jA5qxWxmTFyMwtKBqcRQ_.node = &TM_ffc2zNBeCfY9caiwpQV67xw_0[14];
TM_ffc2zNBeCfY9caiwpQV67xw_0[11].kind = 1;
TM_ffc2zNBeCfY9caiwpQV67xw_0[11].offset = offsetof(tyTuple_CpHT6GSYxsDkQccg9cjxyeQ, Field3);
TM_ffc2zNBeCfY9caiwpQV67xw_0[11].typ = (&NTI_E4jA5qxWxmTFyMwtKBqcRQ_);
TM_ffc2zNBeCfY9caiwpQV67xw_0[11].name = "Field3";
TM_ffc2zNBeCfY9caiwpQV67xw_0[3].len = 4; TM_ffc2zNBeCfY9caiwpQV67xw_0[3].kind = 2; TM_ffc2zNBeCfY9caiwpQV67xw_0[3].sons = &TM_ffc2zNBeCfY9caiwpQV67xw_5[0];
NTI_CpHT6GSYxsDkQccg9cjxyeQ_.node = &TM_ffc2zNBeCfY9caiwpQV67xw_0[3];
NTI_7XI1p02ImfLQezfcEUv8og_.size = sizeof(tySequence_7XI1p02ImfLQezfcEUv8og*);
NTI_7XI1p02ImfLQezfcEUv8og_.kind = 24;
NTI_7XI1p02ImfLQezfcEUv8og_.base = (&NTI_CpHT6GSYxsDkQccg9cjxyeQ_);
NTI_7XI1p02ImfLQezfcEUv8og_.flags = 2;
NTI_7XI1p02ImfLQezfcEUv8og_.marker = Marker_tySequence_7XI1p02ImfLQezfcEUv8og;
}

