/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/calebwin/Projects/pipelines/pipelines/nimcache/stdlib_strutils.o /home/calebwin/Projects/pipelines/pipelines/nimcache/stdlib_strutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NI tyArray_9cc9aPiDa8VaWjVcFLabEDZQ[256];
N_NIMCALL(NIM_BOOL, nsuIsSpaceAsciiChar)(NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, preprocessSub_IhQT0o4blhF4hbhCz0srsw)(NimStringDesc* sub, NI* a);
N_NIMCALL(NI, findAux_xYftXprbikG4pTQVPGgIjg)(NimStringDesc* s, NimStringDesc* sub, NI start, NI last, tyArray_9cc9aPiDa8VaWjVcFLabEDZQ a);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
STRING_LITERAL(TM_JGc9b9bh2D3nTdUR7TGyq8aA_2, "", 0);
STRING_LITERAL(TM_JGc9b9bh2D3nTdUR7TGyq8aA_3, "\012", 1);

N_NIMCALL(NIM_BOOL, nsuIsSpaceAsciiChar)(NIM_CHAR c) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = (((NU8)(c)) == ((NU8)(32)) || ((NU8)(c)) == ((NU8)(9)) || ((NU8)(c)) == ((NU8)(11)) || ((NU8)(c)) == ((NU8)(13)) || ((NU8)(c)) == ((NU8)(10)) || ((NU8)(c)) == ((NU8)(12)));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NIM_BOOL, nsuIsNilOrWhitespace)(NimStringDesc* s) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!((s ? s->Sup.len : 0) == ((NI) 0))) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	result = NIM_TRUE;
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI) 0);
		L = (s ? s->Sup.len : 0);
		{
			while (1) {
				if (!(i < L)) goto LA7;
				c = s->data[i];
				{
					NIM_BOOL T10_;
					T10_ = (NIM_BOOL)0;
					T10_ = nsuIsSpaceAsciiChar(c);
					if (!!(T10_)) goto LA11_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA11_: ;
				i += ((NI) 1);
			} LA7: ;
		}
	}
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars) {
	NimStringDesc* result;
	NI first;
	NI last;
	result = (NimStringDesc*)0;
	first = ((NI) 0);
	last = (NI)((s ? s->Sup.len : 0) - ((NI) 1));
	{
		if (!leading) goto LA3_;
		{
			while (1) {
				if (!((chars[(NU)(((NU8)(s->data[first])))>>3] &(1U<<((NU)(((NU8)(s->data[first])))&7U)))!=0)) goto LA6;
				first += ((NI) 1);
			} LA6: ;
		}
	}
	LA3_: ;
	{
		if (!trailing) goto LA9_;
		{
			while (1) {
				NIM_BOOL T13_;
				T13_ = (NIM_BOOL)0;
				T13_ = (((NI) 0) <= last);
				if (!(T13_)) goto LA14_;
				T13_ = ((chars[(NU)(((NU8)(s->data[last])))>>3] &(1U<<((NU)(((NU8)(s->data[last])))&7U)))!=0);
				LA14_: ;
				if (!T13_) goto LA12;
				last -= ((NI) 1);
			} LA12: ;
		}
	}
	LA9_: ;
	result = copyStrLast(s, first, last);
	return result;
}

N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last) {
	NI result;
	NI last_2;
	void* found;
{	result = (NI)0;
	{
		if (!(((NI) (last)) == ((NI) 0))) goto LA3_;
		last_2 = (s ? (s->Sup.len-1) : -1);
	}
	goto LA1_;
	LA3_: ;
	{
		last_2 = ((NI) (last));
	}
	LA1_: ;
	found = memchr(((void*) ((&s->data[start]))), sub, (NI)((NI)(last_2 - ((NI) (start))) + ((NI) 1)));
	{
		if (!!((found == 0))) goto LA8_;
		result = (NI)((NU64)(((NI) (found))) - (NU64)(((NI) (s->data))));
		goto BeforeRet_;
	}
	LA8_: ;
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars, NI start, NI last) {
	NI result;
	NI last_2;
{	result = (NI)0;
	{
		if (!(((NI) (last)) == ((NI) 0))) goto LA3_;
		last_2 = (s ? (s->Sup.len-1) : -1);
	}
	goto LA1_;
	LA3_: ;
	{
		last_2 = ((NI) (last));
	}
	LA1_: ;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) (start));
		{
			while (1) {
				if (!(res <= last_2)) goto LA8;
				i = res;
				{
					if (!((chars[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0)) goto LA11_;
					result = i;
					goto BeforeRet_;
				}
				LA11_: ;
				res += ((NI) 1);
			} LA8: ;
		}
	}
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, preprocessSub_IhQT0o4blhF4hbhCz0srsw)(NimStringDesc* sub, NI* a) {
	NI m;
	m = (sub ? sub->Sup.len : 0);
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 255))) goto LA3;
				i = res;
				a[(((NU8)(((NIM_CHAR) (((NI) (i)))))))- 0] = (NI)(m + ((NI) 1));
				res += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NI i_2;
		NI colontmp_;
		NI res_2;
		i_2 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(m - ((NI) 1));
		res_2 = ((NI) 0);
		{
			while (1) {
				if (!(res_2 <= colontmp_)) goto LA6;
				i_2 = res_2;
				a[(((NU8)(sub->data[i_2])))- 0] = (NI)(m - i_2);
				res_2 += ((NI) 1);
			} LA6: ;
		}
	}
}

N_NIMCALL(NI, findAux_xYftXprbikG4pTQVPGgIjg)(NimStringDesc* s, NimStringDesc* sub, NI start, NI last, tyArray_9cc9aPiDa8VaWjVcFLabEDZQ a) {
	NI result;
	NI m;
	NI n;
	NI j;
{	result = (NI)0;
	m = (sub ? sub->Sup.len : 0);
	n = (NI)(last + ((NI) 1));
	j = start;
	{
		while (1) {
			if (!(j <= (NI)(n - m))) goto LA2;
			{
				{
					NI k;
					NI colontmp_;
					NI res;
					k = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(m - ((NI) 1));
					res = ((NI) 0);
					{
						while (1) {
							if (!(res <= colontmp_)) goto LA6;
							k = res;
							{
								if (!!(((NU8)(sub->data[k]) == (NU8)(s->data[(NI)(k + j)])))) goto LA9_;
								goto LA3;
							}
							LA9_: ;
							res += ((NI) 1);
						} LA6: ;
					}
				}
				result = j;
				goto BeforeRet_;
			} LA3: ;
			j += a[(((NU8)(s->data[(NI)(j + m)])))- 0];
		} LA2: ;
	}
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by) {
	NimStringDesc* result;
	tyArray_9cc9aPiDa8VaWjVcFLabEDZQ a;
	NI last;
	NI i;
	NimStringDesc* T8_;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_JGc9b9bh2D3nTdUR7TGyq8aA_2));
	preprocessSub_IhQT0o4blhF4hbhCz0srsw(sub, a);
	last = (s ? (s->Sup.len-1) : -1);
	i = ((NI) 0);
	{
		while (1) {
			NI j;
			NimStringDesc* T7_;
			j = findAux_xYftXprbikG4pTQVPGgIjg(s, sub, i, last, a);
			{
				if (!(j < ((NI) 0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
			T7_ = (NimStringDesc*)0;
			T7_ = copyStrLast(s, i, (NI)(j - ((NI) 1)));
			result = resizeString(result, T7_->Sup.len + 0);
appendString(result, T7_);
			result = resizeString(result, by->Sup.len + 0);
appendString(result, by);
			i = (NI)(j + (sub ? sub->Sup.len : 0));
		}
	} LA1: ;
	T8_ = (NimStringDesc*)0;
	T8_ = copyStr(s, i);
	result = resizeString(result, T8_->Sup.len + 0);
appendString(result, T8_);
	return result;
}

N_NIMCALL(NIM_BOOL, substrEq_7ngl0F5lryTkSAj7sYQ7pw)(NimStringDesc* s, NI pos, NimStringDesc* substr) {
	NIM_BOOL result;
	NI i;
	NI length;
{	result = (NIM_BOOL)0;
	i = ((NI) 0);
	length = (substr ? substr->Sup.len : 0);
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (i < length);
			if (!(T3_)) goto LA4_;
			T3_ = ((NU8)(s->data[(NI)(pos + i)]) == (NU8)(substr->data[i]));
			LA4_: ;
			if (!T3_) goto LA2;
			i += ((NI) 1);
		} LA2: ;
	}
	result = (i == length);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringDesc* s, NimStringDesc* suffix) {
	NIM_BOOL result;
	NI i;
	NI j;
{	result = (NIM_BOOL)0;
	i = ((NI) 0);
	j = (NI)((s ? s->Sup.len : 0) - (suffix ? suffix->Sup.len : 0));
	{
		while (1) {
			if (!((NU64)((NI)(i + j)) < (NU64)((s ? s->Sup.len : 0)))) goto LA2;
			{
				if (!!(((NU8)(s->data[(NI)(i + j)]) == (NU8)(suffix->data[i])))) goto LA5_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
			LA5_: ;
			i += ((NI) 1);
		} LA2: ;
	}
	{
		if (!((NU8)(suffix->data[i]) == (NU8)(0))) goto LA9_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA9_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, nsuRemoveSuffixString)(NimStringDesc** s, NimStringDesc* suffix) {
	NI newLen;
	newLen = ((*s) ? (*s)->Sup.len : 0);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nsuEndsWith((*s), suffix);
		if (!T3_) goto LA4_;
		newLen -= (suffix ? suffix->Sup.len : 0);
		(*s) = setLengthStr((*s), ((NI) (newLen)));
	}
	LA4_: ;
}

N_NIMCALL(NimStringDesc*, nsuIndent)(NimStringDesc* s, NI count, NimStringDesc* padding) {
	NimStringDesc* result;
	NI i;
	result = (NimStringDesc*)0;
	result = copyString(((NimStringDesc*) &TM_JGc9b9bh2D3nTdUR7TGyq8aA_2));
	i = ((NI) 0);
	{
		NimStringDesc* line;
		NI first;
		NI last;
		line = (NimStringDesc*)0;
		first = ((NI) 0);
		last = ((NI) 0);
		{
			while (1) {
				{
					while (1) {
						if (!!((((NU8)(s->data[last])) == ((NU8)(0)) || ((NU8)(s->data[last])) == ((NU8)(13)) || ((NU8)(s->data[last])) == ((NU8)(10))))) goto LA5;
						last += ((NI) 1);
					} LA5: ;
				}
				line = copyStrLast(s, first, (NI)(last - ((NI) 1)));
				{
					if (!!((i == ((NI) 0)))) goto LA8_;
					result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_JGc9b9bh2D3nTdUR7TGyq8aA_3));
				}
				LA8_: ;
				{
					NI j;
					NI res;
					j = (NI)0;
					res = ((NI) 1);
					{
						while (1) {
							if (!(res <= ((NI) (count)))) goto LA12;
							j = ((NI) (res));
							result = resizeString(result, padding->Sup.len + 0);
appendString(result, padding);
							res += ((NI) 1);
						} LA12: ;
					}
				}
				result = resizeString(result, line->Sup.len + 0);
appendString(result, line);
				i += ((NI) 1);
				{
					if (!((NU8)(s->data[last]) == (NU8)(10))) goto LA15_;
					last += ((NI) 1);
				}
				goto LA13_;
				LA15_: ;
				{
					if (!((NU8)(s->data[last]) == (NU8)(13))) goto LA18_;
					last += ((NI) 1);
					{
						if (!((NU8)(s->data[last]) == (NU8)(10))) goto LA22_;
						last += ((NI) 1);
					}
					LA22_: ;
				}
				goto LA13_;
				LA18_: ;
				{
					goto LA2;
				}
				LA13_: ;
				first = last;
			}
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start) {
	NI result;
	NI realStart;
{	result = (NI)0;
	{
		if (!(start == ((NI) -1))) goto LA3_;
		realStart = (s ? s->Sup.len : 0);
	}
	goto LA1_;
	LA3_: ;
	{
		realStart = start;
	}
	LA1_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(realStart - (sub ? sub->Sup.len : 0));
		res = colontmp_;
		{
			while (1) {
				if (!(((NI) 0) <= res)) goto LA8;
				i = res;
				{
					NI j;
					NI colontmp__2;
					NI res_2;
					j = (NI)0;
					colontmp__2 = (NI)0;
					colontmp__2 = (NI)((sub ? sub->Sup.len : 0) - ((NI) 1));
					res_2 = ((NI) 0);
					{
						while (1) {
							if (!(res_2 <= colontmp__2)) goto LA11;
							j = res_2;
							result = i;
							{
								if (!!(((NU8)(sub->data[j]) == (NU8)(s->data[(NI)(i + j)])))) goto LA14_;
								result = ((NI) -1);
								goto LA9;
							}
							LA14_: ;
							res_2 += ((NI) 1);
						} LA11: ;
					}
				} LA9: ;
				{
					if (!!((result == ((NI) -1)))) goto LA18_;
					goto BeforeRet_;
				}
				LA18_: ;
				res -= ((NI) 1);
			} LA8: ;
		}
	}
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

