/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/calebwin/Projects/pipeline/src/nimcache/pipeline.o /home/calebwin/Projects/pipeline/src/nimcache/pipeline.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_6j25whH7XTBoIXcM0x1T7A tySequence_6j25whH7XTBoIXcM0x1T7A;
typedef struct tyTuple_9cdgeqdY7FRioNKBoD6G66A tyTuple_9cdgeqdY7FRioNKBoD6G66A;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ {
tySequence_6j25whH7XTBoIXcM0x1T7A* data;
NI counter;
};
struct tyTuple_9cdgeqdY7FRioNKBoD6G66A {
NI Field0;
NimStringDesc* Field1;
tyTuple_UV3llMMYFckfui8YMBuUZA Field2;
};
struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg {
NI a;
NI b;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING path);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(NI, tyProc_grsFbooLsFDKsgZemLk4tA) (NCSTRING str);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_6j25whH7XTBoIXcM0x1T7A {
  TGenericSeq Sup;
  tyTuple_9cdgeqdY7FRioNKBoD6G66A data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initTable_ULT5Nh6n23CMlrIkYDrA0w)(NI initialSize, tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* Result);
N_NIMCALL(void, X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t, NimStringDesc* key, tyTuple_UV3llMMYFckfui8YMBuUZA val);
static N_INLINE(NI, rawGet_mUu9aqSOIh112SegIoWSn8Atables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, enlarge_uZDP0GSDo9bUdQjGNn5MUUQ)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t);
N_NIMCALL(void, rawInsert_Ex1BdIhuzCdgDh15MhJUJg)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t, tySequence_6j25whH7XTBoIXcM0x1T7A** data, NimStringDesc* key, tyTuple_UV3llMMYFckfui8YMBuUZA val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_OzOYZdDjeNXX56NGjEdb8Qtables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI hc);
N_NIMCALL(NimStringDesc*, compile_yRlCrCBaVd6dlyekZPc32w)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitWhitespace)(NimStringDesc* s);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, nsuIndent)(NimStringDesc* s, NI count, NimStringDesc* padding);
N_NIMCALL(void, runFile_5CPntwlWIrrur0HQZuCUCg)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, compileFile_5CPntwlWIrrur0HQZuCUCg_2)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(void, writeFile_c1B29b0ZdDRPHc27YaKqwaA)(NimStringDesc* filename, NimStringDesc* content);
N_NIMCALL(void, main_QkzkYHgocTG2Pef9bzDB4lw)(void);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, pipelineDatInit000)(void);
TNimType NTI_UV3llMMYFckfui8YMBuUZA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125184_;
extern tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_125822_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_125943_;
extern tyProc_grsFbooLsFDKsgZemLk4tA Dl_125255_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125923_;
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_6, "from", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_7, "|", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_10, "/", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_18, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_19, "from multiprocessing import Process, Queue\012", 43);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_20, "", 0);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_21, "from ", 5);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_22, " import ", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_23, " as ", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_24, "\012", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_26, "class PipeSentinel: pass\012", 25);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_27, "while True:\012", 12);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_28, "\011input = in_queue.get()\012", 24);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_29, "\011if isinstance(input, PipeSentinel):\012", 37);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_30, "\011\011output = PipeSentinel()\012", 26);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_31, "\011else:\012", 7);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_32, "\011\011output = ", 11);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_33, "(input)\012", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_34, "\011if out_queue is not None:\012", 27);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_35, "\011\011out_queue.put(output)\012", 24);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_36, "\011\011break\012", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_37, "def run_", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_38, "(in_queue, out_queue):\012", 23);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_39, "\011", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_41, "stream = ", 9);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_42, "()\012", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_43, "in_", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_44, " = Queue()\012", 11);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_48, "None", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_49, "_process = Process(target=run_", 30);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_50, ", args=(", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_51, ",", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_52, ",))\012", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_55, "for data in stream:\012", 20);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_56, "\011in_", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_57, ".put(data)\012", 11);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_58, ".put(PipeSentinel())\012", 21);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_59, "_process.start()\012", 17);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_61, "_process.join()\012", 16);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_63, "if __name__ == \"__main__\":\012", 27);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_64, ":", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_65, ".pipeline", 9);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_66, ".py", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_67, "Welcome to Pipeline!", 20);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_68, "v:0.0.1", 7);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_69, "r", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_70, "run", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_71, "c", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_72, "compile", 7);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(378, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_3;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_3 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_3) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_mUu9aqSOIh112SegIoWSn8Atables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_4;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_4 = subInt(((NI) -1), h);
	result = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_4);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_OzOYZdDjeNXX56NGjEdb8Qtables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_5;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_5 = subInt(((NI) -1), h);
	result = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* a;
	NI T1_;
	a = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3404, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(305, "system.nim");
	result.a = a;
	nimln_(306, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, compile_yRlCrCBaVd6dlyekZPc32w)(NimStringDesc* path) {
	NimStringDesc* result;
	NimStringDesc* contents;
	tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ paths;
	tySequence_4eQHGndY6XBYpFOH09apV8Q* pipes;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* tokens;
	NI index;
	NimStringDesc* code;
	NimStringDesc* mainCode;
	NimStringDesc* iteratorModule;
	NimStringDesc* T48_;
	NI pipeIndex;
	NimStringDesc* T77_;
	NimStringDesc* T78_;
	NimStringDesc* T99_;
	NimStringDesc* T100_;
	nimfr_("compile", "pipeline.nim");
	result = (NimStringDesc*)0;
	nimln_(11, "pipeline.nim");
	contents = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(path);
	memset((void*)(&paths), 0, sizeof(paths));
	nimln_(16, "pipeline.nim");
	chckNil((void*)(&paths));
	memset((void*)(&paths), 0, sizeof(paths));
	initTable_ULT5Nh6n23CMlrIkYDrA0w(((NI) 64), (&paths));
	nimln_(17, "pipeline.nim");
	pipes = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeq((&NTI_4eQHGndY6XBYpFOH09apV8Q_), 0);
	nimln_(20, "pipeline.nim");
	tokens = nsuSplitWhitespace(contents);
	nimln_(23, "pipeline.nim");
	index = ((NI) 0);
	{
		NimStringDesc* token;
		NI i;
		NI L;
		NI T2_;
		token = (NimStringDesc*)0;
		nimln_(3639, "system.nim");
		i = ((NI) 0);
		nimln_(3640, "system.nim");
		T2_ = (tokens ? tokens->Sup.len : 0);
		L = T2_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_16;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_17;
				if (!(i < L)) goto LA4;
				nimln_(3642, "system.nim");
				if ((NU)(i) >= (NU)(tokens->Sup.len)) raiseIndexError();
				token = tokens->data[i];
				nimln_(25, "pipeline.nim");
				if (eqStrings(token, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_6))) goto LA5_;
				if (eqStrings(token, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_7))) goto LA6_;
				goto LA7_;
				LA5_: ;
				{
					NimStringDesc* nextToken;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_8;
					NimStringDesc* newPathAlias;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_9;
					NimStringDesc* newPathModule;
					NI T10_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_11;
					tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T11_;
					NimStringDesc* newPathFunction;
					NI T12_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_12;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_13;
					tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T13_;
					tyTuple_UV3llMMYFckfui8YMBuUZA newPath;
					nimln_(29, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_8 = addInt(index, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_8)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					nextToken = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_8)];
					nimln_(30, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_9 = subInt(index, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_9)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					newPathAlias = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_9)];
					nimln_(31, "pipeline.nim");
					T10_ = (NI)0;
					T10_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(nextToken, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10), ((NI) -1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_11 = subInt(T10_, ((NI) 1));
					T11_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_11));
					newPathModule = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(nextToken, T11_);
					nimln_(32, "pipeline.nim");
					T12_ = (NI)0;
					T12_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(nextToken, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10), ((NI) -1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_12 = addInt(T12_, ((NI) 1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_13 = subInt((nextToken ? nextToken->Sup.len : 0), ((NI) 1));
					T13_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_12), (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_13));
					newPathFunction = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(nextToken, T13_);
					memset((void*)(&newPath), 0, sizeof(newPath));
					nimln_(33, "pipeline.nim");
					newPath.Field0 = copyString(newPathModule);
					newPath.Field1 = copyString(newPathFunction);
					nimln_(36, "pipeline.nim");
					X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA((&paths), newPathAlias, newPath);
				}
				goto LA8_;
				LA6_: ;
				{
					NimStringDesc* prevToken;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_14;
					NimStringDesc* nextToken_2;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_15;
					NimStringDesc* newPipeOrigin;
					NimStringDesc* newPipeDestination;
					tyTuple_UV3llMMYFckfui8YMBuUZA newPipe;
					NI T15_;
					NimStringDesc* T16_;
					NimStringDesc* T17_;
					nimln_(40, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_14 = subInt(index, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_14)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					prevToken = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_14)];
					nimln_(41, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_15 = addInt(index, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_15)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					nextToken_2 = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_15)];
					nimln_(42, "pipeline.nim");
					newPipeOrigin = prevToken;
					nimln_(43, "pipeline.nim");
					newPipeDestination = nextToken_2;
					memset((void*)(&newPipe), 0, sizeof(newPipe));
					nimln_(44, "pipeline.nim");
					newPipe.Field0 = copyString(newPipeOrigin);
					newPipe.Field1 = copyString(newPipeDestination);
					nimln_(47, "pipeline.nim");
					pipes = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) incrSeqV2(&(pipes)->Sup, sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA));
					T15_ = pipes->Sup.len++;
					T16_ = (NimStringDesc*)0;
					T16_ = pipes->data[T15_].Field0; pipes->data[T15_].Field0 = copyStringRC1(newPipe.Field0);
					if (T16_) nimGCunrefNoCycle(T16_);
					T17_ = (NimStringDesc*)0;
					T17_ = pipes->data[T15_].Field1; pipes->data[T15_].Field1 = copyStringRC1(newPipe.Field1);
					if (T17_) nimGCunrefNoCycle(T17_);
				}
				goto LA8_;
				LA7_: ;
				{
				}
				LA8_: ;
				nimln_(52, "pipeline.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_16 = addInt(index, ((NI) 1));
				index = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_16);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_17 = addInt(i, ((NI) 1));
				i = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_17);
				nimln_(3644, "system.nim");
				{
					NI T21_;
					T21_ = (tokens ? tokens->Sup.len : 0);
					if (!!((T21_ == L))) goto LA22_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA22_: ;
			} LA4: ;
		}
	}
	nimln_(58, "pipeline.nim");
	code = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_19));
	nimln_(59, "pipeline.nim");
	mainCode = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_20));
	{
		NimStringDesc* alias;
		tyTuple_UV3llMMYFckfui8YMBuUZA path_2;
		alias = (NimStringDesc*)0;
		memset((void*)(&path_2), 0, sizeof(path_2));
		{
			NI h;
			NI colontmp_;
			NI T26_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(244, "tables.nim");
			T26_ = (paths.data ? (paths.data->Sup.len-1) : -1);
			colontmp_ = T26_;
			nimln_(1986, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_25;
					if (!(res <= colontmp_)) goto LA28;
					nimln_(1988, "system.nim");
					h = res;
					nimln_(245, "tables.nim");
					{
						NIM_BOOL T31_;
						NimStringDesc* T34_;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						T31_ = (NIM_BOOL)0;
						T31_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(paths.data->data[h].Field0);
						if (!T31_) goto LA32_;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						alias = paths.data->data[h].Field1;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						path_2.Field0 = paths.data->data[h].Field2.Field0;
						path_2.Field1 = paths.data->data[h].Field2.Field1;
						nimln_(65, "pipeline.nim");
						T34_ = (NimStringDesc*)0;
						T34_ = rawNewString(path_2.Field0->Sup.len + path_2.Field1->Sup.len + alias->Sup.len + 18);
appendString(T34_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_21));
appendString(T34_, path_2.Field0);
appendString(T34_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_22));
appendString(T34_, path_2.Field1);
appendString(T34_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_23));
appendString(T34_, alias);
appendString(T34_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_24));
						code = resizeString(code, T34_->Sup.len + 0);
appendString(code, T34_);
					}
					LA32_: ;
					nimln_(1989, "system.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_25 = addInt(res, ((NI) 1));
					res = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_25);
				} LA28: ;
			}
		}
	}
	nimln_(70, "pipeline.nim");
	code = resizeString(code, 25);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_26));
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA pipe;
		NI i_2;
		NI L_2;
		NI T36_;
		memset((void*)(&pipe), 0, sizeof(pipe));
		nimln_(3639, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3640, "system.nim");
		T36_ = (pipes ? pipes->Sup.len : 0);
		L_2 = T36_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component;
				NimStringDesc* componentCode;
				NimStringDesc* T39_;
				NimStringDesc* T40_;
				NimStringDesc* T41_;
				NimStringDesc* T42_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_40;
				if (!(i_2 < L_2)) goto LA38;
				nimln_(3642, "system.nim");
				if ((NU)(i_2) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe.Field0 = pipes->data[i_2].Field0;
				pipe.Field1 = pipes->data[i_2].Field1;
				nimln_(74, "pipeline.nim");
				component = pipe.Field1;
				nimln_(76, "pipeline.nim");
				componentCode = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_20));
				nimln_(79, "pipeline.nim");
				componentCode = resizeString(componentCode, 12);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_27));
				nimln_(82, "pipeline.nim");
				componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_28));
				nimln_(86, "pipeline.nim");
				componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_29));
				nimln_(89, "pipeline.nim");
				componentCode = resizeString(componentCode, 26);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_30));
				nimln_(92, "pipeline.nim");
				componentCode = resizeString(componentCode, 7);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_31));
				nimln_(95, "pipeline.nim");
				T39_ = (NimStringDesc*)0;
				T39_ = rawNewString(component->Sup.len + 19);
appendString(T39_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_32));
appendString(T39_, component);
appendString(T39_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_33));
				componentCode = resizeString(componentCode, T39_->Sup.len + 0);
appendString(componentCode, T39_);
				nimln_(98, "pipeline.nim");
				componentCode = resizeString(componentCode, 27);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_34));
				nimln_(101, "pipeline.nim");
				componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_35));
				nimln_(104, "pipeline.nim");
				componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_29));
				nimln_(105, "pipeline.nim");
				componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_36));
				nimln_(108, "pipeline.nim");
				T40_ = (NimStringDesc*)0;
				T40_ = rawNewString(component->Sup.len + 31);
appendString(T40_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_37));
appendString(T40_, component);
appendString(T40_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_38));
				code = resizeString(code, T40_->Sup.len + 0);
appendString(code, T40_);
				nimln_(109, "pipeline.nim");
				T41_ = (NimStringDesc*)0;
				T42_ = (NimStringDesc*)0;
				T42_ = nsuIndent(componentCode, ((NI) 1), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_39));
				T41_ = rawNewString(T42_->Sup.len + 1);
appendString(T41_, T42_);
appendString(T41_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_24));
				code = resizeString(code, T41_->Sup.len + 0);
appendString(code, T41_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_40 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_40);
				nimln_(3644, "system.nim");
				{
					NI T45_;
					T45_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T45_ == L_2))) goto LA46_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA46_: ;
			} LA38: ;
		}
	}
	nimln_(114, "pipeline.nim");
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	iteratorModule = pipes->data[((NI) 0)].Field0;
	nimln_(115, "pipeline.nim");
	T48_ = (NimStringDesc*)0;
	T48_ = rawNewString(iteratorModule->Sup.len + 12);
appendString(T48_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
appendString(T48_, iteratorModule);
appendString(T48_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_42));
	mainCode = resizeString(mainCode, T48_->Sup.len + 0);
appendString(mainCode, T48_);
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA pipe_2;
		NI i_3;
		NI L_3;
		NI T50_;
		memset((void*)(&pipe_2), 0, sizeof(pipe_2));
		nimln_(3639, "system.nim");
		i_3 = ((NI) 0);
		nimln_(3640, "system.nim");
		T50_ = (pipes ? pipes->Sup.len : 0);
		L_3 = T50_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_2;
				NimStringDesc* T53_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_45;
				if (!(i_3 < L_3)) goto LA52;
				nimln_(3642, "system.nim");
				if ((NU)(i_3) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_2.Field0 = pipes->data[i_3].Field0;
				pipe_2.Field1 = pipes->data[i_3].Field1;
				nimln_(119, "pipeline.nim");
				component_2 = pipe_2.Field1;
				nimln_(122, "pipeline.nim");
				T53_ = (NimStringDesc*)0;
				T53_ = rawNewString(component_2->Sup.len + 14);
appendString(T53_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_43));
appendString(T53_, component_2);
appendString(T53_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_44));
				mainCode = resizeString(mainCode, T53_->Sup.len + 0);
appendString(mainCode, T53_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_45 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_45);
				nimln_(3644, "system.nim");
				{
					NI T56_;
					T56_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T56_ == L_3))) goto LA57_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA57_: ;
			} LA52: ;
		}
	}
	nimln_(125, "pipeline.nim");
	pipeIndex = ((NI) 0);
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA pipe_3;
		NI i_4;
		NI L_4;
		NI T60_;
		memset((void*)(&pipe_3), 0, sizeof(pipe_3));
		nimln_(3639, "system.nim");
		i_4 = ((NI) 0);
		nimln_(3640, "system.nim");
		T60_ = (pipes ? pipes->Sup.len : 0);
		L_4 = T60_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_3;
				NimStringDesc* componentQueue;
				NimStringDesc* T63_;
				NimStringDesc* nextComponentQueue;
				NimStringDesc* T71_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_53;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_54;
				if (!(i_4 < L_4)) goto LA62;
				nimln_(3642, "system.nim");
				if ((NU)(i_4) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_3.Field0 = pipes->data[i_4].Field0;
				pipe_3.Field1 = pipes->data[i_4].Field1;
				nimln_(128, "pipeline.nim");
				if ((NU)(pipeIndex) >= (NU)(pipes->Sup.len)) raiseIndexError();
				component_3 = pipes->data[pipeIndex].Field1;
				nimln_(129, "pipeline.nim");
				T63_ = (NimStringDesc*)0;
				T63_ = rawNewString(component_3->Sup.len + 3);
appendString(T63_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_43));
appendString(T63_, component_3);
				componentQueue = T63_;
				nimln_(130, "pipeline.nim");
				{
					NI T66_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_46;
					NimStringDesc* T69_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_47;
					T66_ = (pipes ? pipes->Sup.len : 0);
					TM_tTXdAEOT2QIDPKqCGS4wCw_46 = subInt(T66_, ((NI) 1));
					if (!(pipeIndex < (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_46))) goto LA67_;
					T69_ = (NimStringDesc*)0;
					TM_tTXdAEOT2QIDPKqCGS4wCw_47 = addInt(pipeIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_47)) >= (NU)(pipes->Sup.len)) raiseIndexError();
					T69_ = rawNewString(pipes->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_47)].Field1->Sup.len + 3);
appendString(T69_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_43));
appendString(T69_, pipes->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_47)].Field1);
					nextComponentQueue = T69_;
				}
				goto LA64_;
				LA67_: ;
				{
					nextComponentQueue = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_48));
				}
				LA64_: ;
				nimln_(133, "pipeline.nim");
				T71_ = (NimStringDesc*)0;
				T71_ = rawNewString(component_3->Sup.len + component_3->Sup.len + componentQueue->Sup.len + nextComponentQueue->Sup.len + 43);
appendString(T71_, component_3);
appendString(T71_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_49));
appendString(T71_, component_3);
appendString(T71_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_50));
appendString(T71_, componentQueue);
appendString(T71_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_51));
appendString(T71_, nextComponentQueue);
appendString(T71_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_52));
				mainCode = resizeString(mainCode, T71_->Sup.len + 0);
appendString(mainCode, T71_);
				nimln_(136, "pipeline.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_53 = addInt(pipeIndex, ((NI) 1));
				pipeIndex = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_53);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_54 = addInt(i_4, ((NI) 1));
				i_4 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_54);
				nimln_(3644, "system.nim");
				{
					NI T74_;
					T74_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T74_ == L_4))) goto LA75_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA75_: ;
			} LA62: ;
		}
	}
	nimln_(139, "pipeline.nim");
	mainCode = resizeString(mainCode, 20);
appendString(mainCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_55));
	nimln_(140, "pipeline.nim");
	T77_ = (NimStringDesc*)0;
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	T77_ = rawNewString(pipes->data[((NI) 0)].Field1->Sup.len + 15);
appendString(T77_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_56));
appendString(T77_, pipes->data[((NI) 0)].Field1);
appendString(T77_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_57));
	mainCode = resizeString(mainCode, T77_->Sup.len + 0);
appendString(mainCode, T77_);
	nimln_(143, "pipeline.nim");
	T78_ = (NimStringDesc*)0;
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	T78_ = rawNewString(pipes->data[((NI) 0)].Field1->Sup.len + 24);
appendString(T78_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_43));
appendString(T78_, pipes->data[((NI) 0)].Field1);
appendString(T78_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_58));
	mainCode = resizeString(mainCode, T78_->Sup.len + 0);
appendString(mainCode, T78_);
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA pipe_4;
		NI i_5;
		NI L_5;
		NI T80_;
		memset((void*)(&pipe_4), 0, sizeof(pipe_4));
		nimln_(3639, "system.nim");
		i_5 = ((NI) 0);
		nimln_(3640, "system.nim");
		T80_ = (pipes ? pipes->Sup.len : 0);
		L_5 = T80_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_4;
				NimStringDesc* T83_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_60;
				if (!(i_5 < L_5)) goto LA82;
				nimln_(3642, "system.nim");
				if ((NU)(i_5) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_4.Field0 = pipes->data[i_5].Field0;
				pipe_4.Field1 = pipes->data[i_5].Field1;
				nimln_(147, "pipeline.nim");
				component_4 = pipe_4.Field1;
				nimln_(150, "pipeline.nim");
				T83_ = (NimStringDesc*)0;
				T83_ = rawNewString(component_4->Sup.len + 17);
appendString(T83_, component_4);
appendString(T83_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_59));
				mainCode = resizeString(mainCode, T83_->Sup.len + 0);
appendString(mainCode, T83_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_60 = addInt(i_5, ((NI) 1));
				i_5 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_60);
				nimln_(3644, "system.nim");
				{
					NI T86_;
					T86_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T86_ == L_5))) goto LA87_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA87_: ;
			} LA82: ;
		}
	}
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA pipe_5;
		NI i_6;
		NI L_6;
		NI T90_;
		memset((void*)(&pipe_5), 0, sizeof(pipe_5));
		nimln_(3639, "system.nim");
		i_6 = ((NI) 0);
		nimln_(3640, "system.nim");
		T90_ = (pipes ? pipes->Sup.len : 0);
		L_6 = T90_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_5;
				NimStringDesc* T93_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_62;
				if (!(i_6 < L_6)) goto LA92;
				nimln_(3642, "system.nim");
				if ((NU)(i_6) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_5.Field0 = pipes->data[i_6].Field0;
				pipe_5.Field1 = pipes->data[i_6].Field1;
				nimln_(154, "pipeline.nim");
				component_5 = pipe_5.Field1;
				nimln_(157, "pipeline.nim");
				T93_ = (NimStringDesc*)0;
				T93_ = rawNewString(component_5->Sup.len + 16);
appendString(T93_, component_5);
appendString(T93_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_61));
				mainCode = resizeString(mainCode, T93_->Sup.len + 0);
appendString(mainCode, T93_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_62 = addInt(i_6, ((NI) 1));
				i_6 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_62);
				nimln_(3644, "system.nim");
				{
					NI T96_;
					T96_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T96_ == L_6))) goto LA97_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18));
				}
				LA97_: ;
			} LA92: ;
		}
	}
	nimln_(160, "pipeline.nim");
	code = resizeString(code, 27);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_63));
	nimln_(161, "pipeline.nim");
	T99_ = (NimStringDesc*)0;
	T100_ = (NimStringDesc*)0;
	T100_ = nsuIndent(mainCode, ((NI) 1), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_39));
	T99_ = rawNewString(T100_->Sup.len + 1);
appendString(T99_, T100_);
appendString(T99_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_24));
	code = resizeString(code, T99_->Sup.len + 0);
appendString(code, T99_);
	nimln_(164, "pipeline.nim");
	result = copyString(code);
	popFrame();
	return result;
}

N_NIMCALL(void, runFile_5CPntwlWIrrur0HQZuCUCg)(NimStringDesc* path) {
	NimStringDesc* code;
	NimStringDesc* T1_;
	NCSTRING T2_;
	NimStringDesc* T3_;
	NI T4_;
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T5_;
	NimStringDesc* T6_;
	NI result;
	nimfr_("runFile", "pipeline.nim");
	nimln_(169, "pipeline.nim");
	code = compile_yRlCrCBaVd6dlyekZPc32w(path);
	nimln_(172, "pipeline.nim");
	Dl_125184_();
	nimln_(175, "pipeline.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NCSTRING)0;
	T2_ = Dl_125943_();
	T3_ = (NimStringDesc*)0;
	T3_ = cstrToNimstr(T2_);
	T4_ = (NI)0;
	T4_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(path, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10), ((NI) -1));
	T5_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), T4_);
	T6_ = (NimStringDesc*)0;
	T6_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(path, T5_);
	T1_ = rawNewString(T3_->Sup.len + T6_->Sup.len + 1);
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_64));
appendString(T1_, T6_);
	Dl_125822_(T1_->data);
	nimln_(178, "pipeline.nim");
	result = Dl_125255_(code->data);
	nimln_(181, "pipeline.nim");
	Dl_125923_();
	popFrame();
}

N_NIMCALL(void, compileFile_5CPntwlWIrrur0HQZuCUCg_2)(NimStringDesc* path) {
	NimStringDesc* code;
	NimStringDesc* targetPath;
	nimfr_("compileFile", "pipeline.nim");
	nimln_(186, "pipeline.nim");
	code = compile_yRlCrCBaVd6dlyekZPc32w(path);
	nimln_(189, "pipeline.nim");
	targetPath = nsuReplaceStr(path, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_65), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_66));
	nimln_(192, "pipeline.nim");
	writeFile_c1B29b0ZdDRPHc27YaKqwaA(targetPath, code);
	popFrame();
}

N_NIMCALL(void, main_QkzkYHgocTG2Pef9bzDB4lw)(void) {
	NI T1_;
	nimfr_("main", "pipeline.nim");
	nimln_(195, "pipeline.nim");
	T1_ = (NI)0;
	T1_ = paramCount_T74rCHY8RMV0X07YnKmggw();
	switch (T1_) {
	case ((NI) 0):
	{
		nimln_(198, "pipeline.nim");
		printf("%s\012", ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_67)? (((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_67))->data:"nil");
		fflush(stdout);
		nimln_(199, "pipeline.nim");
		printf("%s\012", ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_68)? (((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_68))->data:"nil");
		fflush(stdout);
	}
	break;
	case ((NI) 1):
	{
		NimStringDesc* path;
		nimln_(202, "pipeline.nim");
		path = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		nimln_(205, "pipeline.nim");
		runFile_5CPntwlWIrrur0HQZuCUCg(path);
	}
	break;
	case ((NI) 2):
	{
		NimStringDesc* T5_;
		nimln_(207, "pipeline.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_69))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_70))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_71))) goto LA7_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_72))) goto LA7_;
		goto LA8_;
		LA6_: ;
		{
			NimStringDesc* path_2;
			nimln_(210, "pipeline.nim");
			path_2 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			nimln_(213, "pipeline.nim");
			runFile_5CPntwlWIrrur0HQZuCUCg(path_2);
		}
		goto LA9_;
		LA7_: ;
		{
			NimStringDesc* path_3;
			nimln_(216, "pipeline.nim");
			path_3 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			nimln_(219, "pipeline.nim");
			compileFile_5CPntwlWIrrur0HQZuCUCg_2(path_3);
		}
		goto LA9_;
		LA8_: ;
		{
		}
		LA9_: ;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	python_pythonDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	pipelineDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	python_pythonInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("pipeline", "pipeline.nim");
	nimln_(223, "pipeline.nim");
	main_QkzkYHgocTG2Pef9bzDB4lw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, pipelineDatInit000)(void) {
static TNimNode* TM_tTXdAEOT2QIDPKqCGS4wCw_2[2];
static TNimNode TM_tTXdAEOT2QIDPKqCGS4wCw_0[3];
NTI_UV3llMMYFckfui8YMBuUZA_.size = sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA);
NTI_UV3llMMYFckfui8YMBuUZA_.kind = 18;
NTI_UV3llMMYFckfui8YMBuUZA_.base = 0;
NTI_UV3llMMYFckfui8YMBuUZA_.flags = 2;
TM_tTXdAEOT2QIDPKqCGS4wCw_2[0] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[1];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field0);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].name = "Field0";
TM_tTXdAEOT2QIDPKqCGS4wCw_2[1] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[2];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field1);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].name = "Field1";
TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].len = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].kind = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].sons = &TM_tTXdAEOT2QIDPKqCGS4wCw_2[0];
NTI_UV3llMMYFckfui8YMBuUZA_.node = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[0];
NTI_4eQHGndY6XBYpFOH09apV8Q_.size = sizeof(tySequence_4eQHGndY6XBYpFOH09apV8Q*);
NTI_4eQHGndY6XBYpFOH09apV8Q_.kind = 24;
NTI_4eQHGndY6XBYpFOH09apV8Q_.base = (&NTI_UV3llMMYFckfui8YMBuUZA_);
NTI_4eQHGndY6XBYpFOH09apV8Q_.flags = 2;
NTI_4eQHGndY6XBYpFOH09apV8Q_.marker = Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q;
}

