/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/calebwin/Projects/pipeline/src/nimcache/pipeline.o /home/calebwin/Projects/pipeline/src/nimcache/pipeline.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_6j25whH7XTBoIXcM0x1T7A tySequence_6j25whH7XTBoIXcM0x1T7A;
typedef struct tyTuple_9cdgeqdY7FRioNKBoD6G66A tyTuple_9cdgeqdY7FRioNKBoD6G66A;
typedef struct tySequence_6DnSqKvIUhqSESkW5cxf1Q tySequence_6DnSqKvIUhqSESkW5cxf1Q;
typedef struct tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ {
tySequence_6j25whH7XTBoIXcM0x1T7A* data;
NI counter;
};
struct tyTuple_9cdgeqdY7FRioNKBoD6G66A {
NI Field0;
NimStringDesc* Field1;
tyTuple_UV3llMMYFckfui8YMBuUZA Field2;
};
typedef NU8 tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA;
struct tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA Field3;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg {
NI a;
NI b;
};
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING path);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(NI, tyProc_grsFbooLsFDKsgZemLk4tA) (NCSTRING str);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_6DnSqKvIUhqSESkW5cxf1Q {
  TGenericSeq Sup;
  tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_6j25whH7XTBoIXcM0x1T7A {
  TGenericSeq Sup;
  tyTuple_9cdgeqdY7FRioNKBoD6G66A data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, initTable_ULT5Nh6n23CMlrIkYDrA0w)(NI initialSize, tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* Result);
N_NIMCALL(void, X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t, NimStringDesc* key, tyTuple_UV3llMMYFckfui8YMBuUZA val);
static N_INLINE(NI, rawGet_mUu9aqSOIh112SegIoWSn8Atables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI* hc);
N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, enlarge_uZDP0GSDo9bUdQjGNn5MUUQ)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t);
N_NIMCALL(void, rawInsert_Ex1BdIhuzCdgDh15MhJUJg)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ* t, tySequence_6j25whH7XTBoIXcM0x1T7A** data, NimStringDesc* key, tyTuple_UV3llMMYFckfui8YMBuUZA val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_OzOYZdDjeNXX56NGjEdb8Qtables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI hc);
N_NIMCALL(NimStringDesc*, compile_yRlCrCBaVd6dlyekZPc32w)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_6DnSqKvIUhqSESkW5cxf1Q)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NIM_BOOL, nsuIsNilOrWhitespace)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b);
N_NIMCALL(NI, nsuFindChar)(NimStringDesc* s, NIM_CHAR sub, NI start, NI last);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, nsuReplaceStr)(NimStringDesc* s, NimStringDesc* sub, NimStringDesc* by);
N_NIMCALL(void, nsuRemoveSuffixString)(NimStringDesc** s, NimStringDesc* suffix);
N_NIMCALL(NimStringDesc*, nsuIndent)(NimStringDesc* s, NI count, NimStringDesc* padding);
N_NIMCALL(void, runFile_5CPntwlWIrrur0HQZuCUCg)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, compileFile_5CPntwlWIrrur0HQZuCUCg_2)(NimStringDesc* path);
N_NIMCALL(void, writeFile_c1B29b0ZdDRPHc27YaKqwaA)(NimStringDesc* filename, NimStringDesc* content);
N_NIMCALL(void, main_QkzkYHgocTG2Pef9bzDB4lw)(void);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, pipelineDatInit000)(void);
TNimType NTI_UV3llMMYFckfui8YMBuUZA_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_7T6SqU26Y9ca7z9bynTdnpZQ_;
TNimType NTI_7vo6pbCJWqzFxcwxAp9bfIA_;
TNimType NTI_6DnSqKvIUhqSESkW5cxf1Q_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125184_;
extern tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_125822_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_125943_;
extern tyProc_grsFbooLsFDKsgZemLk4tA Dl_125255_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125923_;
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_10, "", 0);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_12, "(", 1);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_tTXdAEOT2QIDPKqCGS4wCw_13 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_16, "from", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_17, "|>", 2);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_18, "/>", 2);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_21, "/", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_30, "where", 5);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_32, "(*)", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_41, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_42, "from multiprocessing import Process, Queue\012", 43);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_43, "from ", 5);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_44, " import ", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_45, " as ", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_46, "\012", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_48, "class PipeSentinel: pass\012", 25);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_49, "def run_", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_50, "(stream, out_queue):\012", 21);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_51, "\011for data in stream:\012", 21);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_52, "\011\011out_queue.put(data)\012", 22);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_53, "\011out_queue.put(PipeSentinel())\012", 31);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_54, "*", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_55, "input", 5);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_56, "while 1:\012", 9);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_57, "\011input = in_queue.get()\012", 24);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_58, "\011if isinstance(input, PipeSentinel):\012", 37);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_59, "\011\011output = PipeSentinel()\012", 26);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_60, "\011else:\012", 7);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_61, "\011\011output = ", 11);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_62, "\011if out_queue is not None:\012", 27);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_63, "\011\011out_queue.put(output)\012", 24);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_64, "\011\011break\012", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_65, "\011\011if ", 5);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_66, ":\012", 2);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_67, "\011\011\011output = input\012", 18);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_68, "\011\011else:\012", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_69, "\011\011\011continue\012", 12);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_70, "(in_queue, out_queue):\012", 23);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_71, "\011", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_73, "stream = ", 9);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_74, "()\012", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_75, "in_", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_76, " = Queue()\012", 11);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_80, "None", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_81, "_process = Process(target=run_", 30);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_82, ", args=(", 8);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_83, ",", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_84, ",))\012", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_87, "run_", 4);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_88, "(stream, in_", 12);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_89, ")\012", 2);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_90, "_process.start()\012", 17);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_92, "_process.join()\012", 16);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_94, "if __name__ == \"__main__\":\012", 27);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_95, ":", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_96, ".pipeline", 9);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_97, ".py", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_98, "Welcome to Pipeline!", 20);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_99, "v:0.0.1", 7);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_100, "r", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_101, "run", 3);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_102, "c", 1);
STRING_LITERAL(TM_tTXdAEOT2QIDPKqCGS4wCw_103, "compile", 7);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(378, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_3;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_3 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_3) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_mUu9aqSOIh112SegIoWSn8Atables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_4;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_4 = subInt(((NI) -1), h);
	result = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_4);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_OzOYZdDjeNXX56NGjEdb8Qtables)(tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_tTXdAEOT2QIDPKqCGS4wCw_5;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_tTXdAEOT2QIDPKqCGS4wCw_5 = subInt(((NI) -1), h);
	result = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_6DnSqKvIUhqSESkW5cxf1Q)(void* p, NI op) {
	tySequence_6DnSqKvIUhqSESkW5cxf1Q* a;
	NI T1_;
	a = (tySequence_6DnSqKvIUhqSESkW5cxf1Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2, op);
	}
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NimStringDesc*, X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem)(NimStringDesc* s, tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg x) {
	NimStringDesc* result;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3404, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg, dotdot__18yoMoUbfoITYgEZSwZDYAtimes)(NI a, NI b) {
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(305, "system.nim");
	result.a = a;
	nimln_(306, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, compile_yRlCrCBaVd6dlyekZPc32w)(NimStringDesc* path) {
	NimStringDesc* result;
	NimStringDesc* contents;
	tyObject_Table_Arx5BCDWxU9b8XM3yeiuphQ paths;
	tySequence_6DnSqKvIUhqSESkW5cxf1Q* pipes;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* tokens;
	NimStringDesc* token;
	NI index;
	NI tokenIndex;
	NimStringDesc* code;
	NimStringDesc* mainCode;
	NimStringDesc* generatorName;
	NimStringDesc* T84_;
	NimStringDesc* iteratorModule;
	NimStringDesc* T101_;
	NI pipeIndex;
	NimStringDesc* T130_;
	NimStringDesc* T151_;
	NimStringDesc* T152_;
	nimfr_("compile", "pipeline.nim");
	result = (NimStringDesc*)0;
	nimln_(15, "pipeline.nim");
	contents = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(path);
	memset((void*)(&paths), 0, sizeof(paths));
	nimln_(20, "pipeline.nim");
	chckNil((void*)(&paths));
	memset((void*)(&paths), 0, sizeof(paths));
	initTable_ULT5Nh6n23CMlrIkYDrA0w(((NI) 64), (&paths));
	nimln_(21, "pipeline.nim");
	pipes = (tySequence_6DnSqKvIUhqSESkW5cxf1Q*) newSeq((&NTI_6DnSqKvIUhqSESkW5cxf1Q_), 0);
	nimln_(25, "pipeline.nim");
	tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(26, "pipeline.nim");
	token = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10));
	nimln_(27, "pipeline.nim");
	index = ((NI) 0);
	{
		nimln_(29, "pipeline.nim");
		while (1) {
			NI TM_tTXdAEOT2QIDPKqCGS4wCw_11;
			NimStringDesc* character;
			TM_tTXdAEOT2QIDPKqCGS4wCw_11 = subInt((contents ? contents->Sup.len : 0), ((NI) 1));
			if (!(index <= (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_11))) goto LA2;
			nimln_(30, "pipeline.nim");
			if ((NU)(index) > (NU)(contents->Sup.len)) raiseIndexError();
			character = nimCharToStr(contents->data[index]);
			nimln_(33, "pipeline.nim");
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = nsuIsNilOrWhitespace(character);
				if (T5_) goto LA6_;
				T5_ = eqStrings(character, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_12));
				LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(34, "pipeline.nim");
				{
					NimStringDesc* T11_;
					NimStringDesc* T14_;
					NI T15_;
					NimStringDesc* T16_;
					T11_ = (NimStringDesc*)0;
					T11_ = nsuStrip(token, NIM_TRUE, NIM_TRUE, TM_tTXdAEOT2QIDPKqCGS4wCw_13);
					if (!(((NI) 0) < (T11_ ? T11_->Sup.len : 0))) goto LA12_;
					nimln_(35, "pipeline.nim");
					T14_ = (NimStringDesc*)0;
					T14_ = nsuStrip(token, NIM_TRUE, NIM_TRUE, TM_tTXdAEOT2QIDPKqCGS4wCw_13);
					tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(tokens)->Sup, sizeof(NimStringDesc*));
					T15_ = tokens->Sup.len++;
					T16_ = (NimStringDesc*)0;
					T16_ = tokens->data[T15_]; tokens->data[T15_] = copyStringRC1(T14_);
					if (T16_) nimGCunrefNoCycle(T16_);
				}
				LA12_: ;
				nimln_(36, "pipeline.nim");
				token = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10));
			}
			LA7_: ;
			nimln_(39, "pipeline.nim");
			{
				NimStringDesc* parameterDeclaration;
				NI T21_;
				tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T22_;
				NI T23_;
				NimStringDesc* T24_;
				NI T25_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_14;
				if (!eqStrings(character, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_12))) goto LA19_;
				nimln_(40, "pipeline.nim");
				T21_ = (NI)0;
				T21_ = nsuFindChar(contents, 41, ((NI)chckRange(index, ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI) 0));
				T22_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(index, T21_);
				parameterDeclaration = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(contents, T22_);
				nimln_(41, "pipeline.nim");
				tokens = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(tokens)->Sup, sizeof(NimStringDesc*));
				T23_ = tokens->Sup.len++;
				T24_ = (NimStringDesc*)0;
				T24_ = tokens->data[T23_]; tokens->data[T23_] = copyStringRC1(parameterDeclaration);
				if (T24_) nimGCunrefNoCycle(T24_);
				nimln_(42, "pipeline.nim");
				T25_ = (NI)0;
				T25_ = nsuFindChar(contents, 41, ((NI)chckRange(index, ((NI) 0), ((NI) IL64(9223372036854775807)))), ((NI) 0));
				TM_tTXdAEOT2QIDPKqCGS4wCw_14 = addInt(T25_, ((NI) 1));
				index = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_14);
			}
			goto LA17_;
			LA19_: ;
			{
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_15;
				nimln_(44, "pipeline.nim");
				token = resizeString(token, character->Sup.len + 0);
appendString(token, character);
				nimln_(46, "pipeline.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_15 = addInt(index, ((NI) 1));
				index = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_15);
			}
			LA17_: ;
		} LA2: ;
	}
	nimln_(49, "pipeline.nim");
	tokenIndex = ((NI) 0);
	{
		NimStringDesc* token_2;
		NI i;
		NI L;
		NI T28_;
		token_2 = (NimStringDesc*)0;
		nimln_(3639, "system.nim");
		i = ((NI) 0);
		nimln_(3640, "system.nim");
		T28_ = (tokens ? tokens->Sup.len : 0);
		L = T28_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_39;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_40;
				if (!(i < L)) goto LA30;
				nimln_(3642, "system.nim");
				if ((NU)(i) >= (NU)(tokens->Sup.len)) raiseIndexError();
				token_2 = tokens->data[i];
				nimln_(51, "pipeline.nim");
				if (eqStrings(token_2, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_16))) goto LA31_;
				if (eqStrings(token_2, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_17))) goto LA32_;
				if (eqStrings(token_2, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_18))) goto LA33_;
				goto LA34_;
				LA31_: ;
				{
					NimStringDesc* nextToken;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_19;
					NimStringDesc* newPathAlias;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_20;
					NimStringDesc* newPathModule;
					NI T37_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_22;
					tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T38_;
					NimStringDesc* newPathFunction;
					NI T39_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_23;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_24;
					tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T40_;
					tyTuple_UV3llMMYFckfui8YMBuUZA newPath;
					nimln_(55, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_19 = addInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_19)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					nextToken = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_19)];
					nimln_(56, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_20 = subInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_20)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					newPathAlias = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_20)];
					nimln_(57, "pipeline.nim");
					T37_ = (NI)0;
					T37_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(nextToken, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_21), ((NI) -1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_22 = subInt(T37_, ((NI) 1));
					T38_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_22));
					newPathModule = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(nextToken, T38_);
					nimln_(58, "pipeline.nim");
					T39_ = (NI)0;
					T39_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(nextToken, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_21), ((NI) -1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_23 = addInt(T39_, ((NI) 1));
					TM_tTXdAEOT2QIDPKqCGS4wCw_24 = subInt((nextToken ? nextToken->Sup.len : 0), ((NI) 1));
					T40_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_23), (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_24));
					newPathFunction = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(nextToken, T40_);
					memset((void*)(&newPath), 0, sizeof(newPath));
					nimln_(59, "pipeline.nim");
					newPath.Field0 = copyString(newPathModule);
					newPath.Field1 = copyString(newPathFunction);
					nimln_(62, "pipeline.nim");
					X5BX5Deq__TXsEPGXBdmgsfc4Umhjt9bA((&paths), newPathAlias, newPath);
				}
				goto LA35_;
				LA32_: ;
				{
					NimStringDesc* prevToken;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_25;
					NimStringDesc* nextToken_2;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_26;
					NimStringDesc* newPipeOrigin;
					NimStringDesc* newPipeDestination;
					NimStringDesc* newPipeParameters;
					tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ newPipe;
					NI T50_;
					NimStringDesc* T51_;
					NimStringDesc* T52_;
					NimStringDesc* T53_;
					nimln_(66, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_25 = subInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_25)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					prevToken = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_25)];
					nimln_(67, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_26 = addInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_26)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					nextToken_2 = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_26)];
					nimln_(68, "pipeline.nim");
					newPipeOrigin = prevToken;
					nimln_(69, "pipeline.nim");
					newPipeDestination = nextToken_2;
					nimln_(70, "pipeline.nim");
					{
						NIM_BOOL T44_;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_27;
						NI T45_;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_28;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_29;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_31;
						T44_ = (NIM_BOOL)0;
						TM_tTXdAEOT2QIDPKqCGS4wCw_27 = addInt(tokenIndex, ((NI) 3));
						T45_ = (tokens ? tokens->Sup.len : 0);
						TM_tTXdAEOT2QIDPKqCGS4wCw_28 = subInt(T45_, ((NI) 1));
						T44_ = ((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_27) <= (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_28));
						if (!(T44_)) goto LA46_;
						TM_tTXdAEOT2QIDPKqCGS4wCw_29 = addInt(tokenIndex, ((NI) 2));
						if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_29)) >= (NU)(tokens->Sup.len)) raiseIndexError();
						T44_ = eqStrings(tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_29)], ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_30));
						LA46_: ;
						if (!T44_) goto LA47_;
						TM_tTXdAEOT2QIDPKqCGS4wCw_31 = addInt(tokenIndex, ((NI) 3));
						if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_31)) >= (NU)(tokens->Sup.len)) raiseIndexError();
						newPipeParameters = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_31)];
					}
					goto LA42_;
					LA47_: ;
					{
						newPipeParameters = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_32));
					}
					LA42_: ;
					memset((void*)(&newPipe), 0, sizeof(newPipe));
					nimln_(71, "pipeline.nim");
					newPipe.Field0 = copyString(newPipeOrigin);
					newPipe.Field1 = copyString(newPipeParameters);
					newPipe.Field2 = copyString(newPipeDestination);
					newPipe.Field3 = ((tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA) 0);
					nimln_(74, "pipeline.nim");
					pipes = (tySequence_6DnSqKvIUhqSESkW5cxf1Q*) incrSeqV2(&(pipes)->Sup, sizeof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ));
					T50_ = pipes->Sup.len++;
					T51_ = (NimStringDesc*)0;
					T51_ = pipes->data[T50_].Field0; pipes->data[T50_].Field0 = copyStringRC1(newPipe.Field0);
					if (T51_) nimGCunrefNoCycle(T51_);
					T52_ = (NimStringDesc*)0;
					T52_ = pipes->data[T50_].Field1; pipes->data[T50_].Field1 = copyStringRC1(newPipe.Field1);
					if (T52_) nimGCunrefNoCycle(T52_);
					T53_ = (NimStringDesc*)0;
					T53_ = pipes->data[T50_].Field2; pipes->data[T50_].Field2 = copyStringRC1(newPipe.Field2);
					if (T53_) nimGCunrefNoCycle(T53_);
					pipes->data[T50_].Field3 = newPipe.Field3;
				}
				goto LA35_;
				LA33_: ;
				{
					NimStringDesc* prevToken_2;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_33;
					NimStringDesc* nextToken_3;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_34;
					NimStringDesc* newPipeOrigin_2;
					NimStringDesc* newPipeDestination_2;
					NimStringDesc* newPipeParameters_2;
					tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ newPipe_2;
					NI T63_;
					NimStringDesc* T64_;
					NimStringDesc* T65_;
					NimStringDesc* T66_;
					nimln_(78, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_33 = subInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_33)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					prevToken_2 = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_33)];
					nimln_(79, "pipeline.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_34 = addInt(tokenIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_34)) >= (NU)(tokens->Sup.len)) raiseIndexError();
					nextToken_3 = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_34)];
					nimln_(80, "pipeline.nim");
					newPipeOrigin_2 = prevToken_2;
					nimln_(81, "pipeline.nim");
					newPipeDestination_2 = nextToken_3;
					nimln_(82, "pipeline.nim");
					{
						NIM_BOOL T57_;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_35;
						NI T58_;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_36;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_37;
						NI TM_tTXdAEOT2QIDPKqCGS4wCw_38;
						T57_ = (NIM_BOOL)0;
						TM_tTXdAEOT2QIDPKqCGS4wCw_35 = addInt(tokenIndex, ((NI) 3));
						T58_ = (tokens ? tokens->Sup.len : 0);
						TM_tTXdAEOT2QIDPKqCGS4wCw_36 = subInt(T58_, ((NI) 1));
						T57_ = ((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_35) <= (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_36));
						if (!(T57_)) goto LA59_;
						TM_tTXdAEOT2QIDPKqCGS4wCw_37 = addInt(tokenIndex, ((NI) 2));
						if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_37)) >= (NU)(tokens->Sup.len)) raiseIndexError();
						T57_ = eqStrings(tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_37)], ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_30));
						LA59_: ;
						if (!T57_) goto LA60_;
						TM_tTXdAEOT2QIDPKqCGS4wCw_38 = addInt(tokenIndex, ((NI) 3));
						if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_38)) >= (NU)(tokens->Sup.len)) raiseIndexError();
						newPipeParameters_2 = tokens->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_38)];
					}
					goto LA55_;
					LA60_: ;
					{
						newPipeParameters_2 = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_32));
					}
					LA55_: ;
					memset((void*)(&newPipe_2), 0, sizeof(newPipe_2));
					nimln_(83, "pipeline.nim");
					newPipe_2.Field0 = copyString(newPipeOrigin_2);
					newPipe_2.Field1 = copyString(newPipeParameters_2);
					newPipe_2.Field2 = copyString(newPipeDestination_2);
					newPipe_2.Field3 = ((tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA) 1);
					nimln_(86, "pipeline.nim");
					pipes = (tySequence_6DnSqKvIUhqSESkW5cxf1Q*) incrSeqV2(&(pipes)->Sup, sizeof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ));
					T63_ = pipes->Sup.len++;
					T64_ = (NimStringDesc*)0;
					T64_ = pipes->data[T63_].Field0; pipes->data[T63_].Field0 = copyStringRC1(newPipe_2.Field0);
					if (T64_) nimGCunrefNoCycle(T64_);
					T65_ = (NimStringDesc*)0;
					T65_ = pipes->data[T63_].Field1; pipes->data[T63_].Field1 = copyStringRC1(newPipe_2.Field1);
					if (T65_) nimGCunrefNoCycle(T65_);
					T66_ = (NimStringDesc*)0;
					T66_ = pipes->data[T63_].Field2; pipes->data[T63_].Field2 = copyStringRC1(newPipe_2.Field2);
					if (T66_) nimGCunrefNoCycle(T66_);
					pipes->data[T63_].Field3 = newPipe_2.Field3;
				}
				goto LA35_;
				LA34_: ;
				{
				}
				LA35_: ;
				nimln_(91, "pipeline.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_39 = addInt(tokenIndex, ((NI) 1));
				tokenIndex = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_39);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_40 = addInt(i, ((NI) 1));
				i = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_40);
				nimln_(3644, "system.nim");
				{
					NI T70_;
					T70_ = (tokens ? tokens->Sup.len : 0);
					if (!!((T70_ == L))) goto LA71_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA71_: ;
			} LA30: ;
		}
	}
	nimln_(97, "pipeline.nim");
	code = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_42));
	nimln_(98, "pipeline.nim");
	mainCode = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10));
	{
		NimStringDesc* alias;
		tyTuple_UV3llMMYFckfui8YMBuUZA path_2;
		alias = (NimStringDesc*)0;
		memset((void*)(&path_2), 0, sizeof(path_2));
		{
			NI h;
			NI colontmp_;
			NI T75_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(244, "tables.nim");
			T75_ = (paths.data ? (paths.data->Sup.len-1) : -1);
			colontmp_ = T75_;
			nimln_(1986, "system.nim");
			res = ((NI) 0);
			{
				nimln_(1987, "system.nim");
				while (1) {
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_47;
					if (!(res <= colontmp_)) goto LA77;
					nimln_(1988, "system.nim");
					h = res;
					nimln_(245, "tables.nim");
					{
						NIM_BOOL T80_;
						NimStringDesc* T83_;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						T80_ = (NIM_BOOL)0;
						T80_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(paths.data->data[h].Field0);
						if (!T80_) goto LA81_;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						alias = paths.data->data[h].Field1;
						if ((NU)(h) >= (NU)(paths.data->Sup.len)) raiseIndexError();
						path_2.Field0 = paths.data->data[h].Field2.Field0;
						path_2.Field1 = paths.data->data[h].Field2.Field1;
						nimln_(104, "pipeline.nim");
						T83_ = (NimStringDesc*)0;
						T83_ = rawNewString(path_2.Field0->Sup.len + path_2.Field1->Sup.len + alias->Sup.len + 18);
appendString(T83_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_43));
appendString(T83_, path_2.Field0);
appendString(T83_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_44));
appendString(T83_, path_2.Field1);
appendString(T83_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_45));
appendString(T83_, alias);
appendString(T83_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
						code = resizeString(code, T83_->Sup.len + 0);
appendString(code, T83_);
					}
					LA81_: ;
					nimln_(1989, "system.nim");
					TM_tTXdAEOT2QIDPKqCGS4wCw_47 = addInt(res, ((NI) 1));
					res = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_47);
				} LA77: ;
			}
		}
	}
	nimln_(109, "pipeline.nim");
	code = resizeString(code, 25);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_48));
	nimln_(112, "pipeline.nim");
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	generatorName = pipes->data[((NI) 0)].Field0;
	nimln_(114, "pipeline.nim");
	T84_ = (NimStringDesc*)0;
	T84_ = rawNewString(generatorName->Sup.len + 29);
appendString(T84_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_49));
appendString(T84_, generatorName);
appendString(T84_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_50));
	code = resizeString(code, T84_->Sup.len + 0);
appendString(code, T84_);
	nimln_(115, "pipeline.nim");
	code = resizeString(code, 21);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_51));
	nimln_(116, "pipeline.nim");
	code = resizeString(code, 22);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_52));
	nimln_(117, "pipeline.nim");
	code = resizeString(code, 31);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_53));
	{
		tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ pipe;
		NI i_2;
		NI L_2;
		NI T86_;
		memset((void*)(&pipe), 0, sizeof(pipe));
		nimln_(3639, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3640, "system.nim");
		T86_ = (pipes ? pipes->Sup.len : 0);
		L_2 = T86_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component;
				NimStringDesc* parameters;
				NimStringDesc* componentCode;
				NimStringDesc* T93_;
				NimStringDesc* T94_;
				NimStringDesc* T95_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_72;
				if (!(i_2 < L_2)) goto LA88;
				nimln_(3642, "system.nim");
				if ((NU)(i_2) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe.Field0 = pipes->data[i_2].Field0;
				pipe.Field1 = pipes->data[i_2].Field1;
				pipe.Field2 = pipes->data[i_2].Field2;
				pipe.Field3 = pipes->data[i_2].Field3;
				nimln_(122, "pipeline.nim");
				component = pipe.Field2;
				nimln_(123, "pipeline.nim");
				parameters = nsuReplaceStr(pipe.Field1, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_54), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_55));
				nimln_(125, "pipeline.nim");
				componentCode = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_10));
				nimln_(127, "pipeline.nim");
				switch (pipe.Field3) {
				case ((tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA) 0):
				{
					NimStringDesc* T90_;
					nimln_(131, "pipeline.nim");
					componentCode = resizeString(componentCode, 9);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_56));
					nimln_(134, "pipeline.nim");
					componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_57));
					nimln_(138, "pipeline.nim");
					componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_58));
					nimln_(141, "pipeline.nim");
					componentCode = resizeString(componentCode, 26);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_59));
					nimln_(144, "pipeline.nim");
					componentCode = resizeString(componentCode, 7);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_60));
					nimln_(147, "pipeline.nim");
					T90_ = (NimStringDesc*)0;
					T90_ = rawNewString(component->Sup.len + parameters->Sup.len + 12);
appendString(T90_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_61));
appendString(T90_, component);
appendString(T90_, parameters);
appendString(T90_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
					componentCode = resizeString(componentCode, T90_->Sup.len + 0);
appendString(componentCode, T90_);
					nimln_(150, "pipeline.nim");
					componentCode = resizeString(componentCode, 27);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_62));
					nimln_(153, "pipeline.nim");
					componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_63));
					nimln_(156, "pipeline.nim");
					componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_58));
					nimln_(157, "pipeline.nim");
					componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_64));
				}
				break;
				case ((tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA) 1):
				{
					NimStringDesc* T92_;
					nimln_(161, "pipeline.nim");
					componentCode = resizeString(componentCode, 9);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_56));
					nimln_(164, "pipeline.nim");
					componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_57));
					nimln_(168, "pipeline.nim");
					componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_58));
					nimln_(170, "pipeline.nim");
					componentCode = resizeString(componentCode, 26);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_59));
					nimln_(173, "pipeline.nim");
					componentCode = resizeString(componentCode, 7);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_60));
					nimln_(174, "pipeline.nim");
					T92_ = (NimStringDesc*)0;
					T92_ = rawNewString(component->Sup.len + parameters->Sup.len + 7);
appendString(T92_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_65));
appendString(T92_, component);
appendString(T92_, parameters);
appendString(T92_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_66));
					componentCode = resizeString(componentCode, T92_->Sup.len + 0);
appendString(componentCode, T92_);
					nimln_(175, "pipeline.nim");
					componentCode = resizeString(componentCode, 18);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_67));
					nimln_(176, "pipeline.nim");
					componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_68));
					nimln_(177, "pipeline.nim");
					componentCode = resizeString(componentCode, 12);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_69));
					nimln_(180, "pipeline.nim");
					componentCode = resizeString(componentCode, 27);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_62));
					nimln_(182, "pipeline.nim");
					componentCode = resizeString(componentCode, 24);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_63));
					nimln_(185, "pipeline.nim");
					componentCode = resizeString(componentCode, 37);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_58));
					nimln_(186, "pipeline.nim");
					componentCode = resizeString(componentCode, 8);
appendString(componentCode, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_64));
				}
				break;
				}
				nimln_(189, "pipeline.nim");
				T93_ = (NimStringDesc*)0;
				T93_ = rawNewString(component->Sup.len + 31);
appendString(T93_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_49));
appendString(T93_, component);
appendString(T93_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_70));
				code = resizeString(code, T93_->Sup.len + 0);
appendString(code, T93_);
				nimln_(190, "pipeline.nim");
				nsuRemoveSuffixString((&componentCode), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
				nimln_(191, "pipeline.nim");
				T94_ = (NimStringDesc*)0;
				T95_ = (NimStringDesc*)0;
				T95_ = nsuIndent(componentCode, ((NI) 1), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_71));
				T94_ = rawNewString(T95_->Sup.len + 1);
appendString(T94_, T95_);
appendString(T94_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
				code = resizeString(code, T94_->Sup.len + 0);
appendString(code, T94_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_72 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_72);
				nimln_(3644, "system.nim");
				{
					NI T98_;
					T98_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T98_ == L_2))) goto LA99_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA99_: ;
			} LA88: ;
		}
	}
	nimln_(196, "pipeline.nim");
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	iteratorModule = pipes->data[((NI) 0)].Field0;
	nimln_(197, "pipeline.nim");
	T101_ = (NimStringDesc*)0;
	T101_ = rawNewString(iteratorModule->Sup.len + 12);
appendString(T101_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_73));
appendString(T101_, iteratorModule);
appendString(T101_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_74));
	mainCode = resizeString(mainCode, T101_->Sup.len + 0);
appendString(mainCode, T101_);
	{
		tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ pipe_2;
		NI i_3;
		NI L_3;
		NI T103_;
		memset((void*)(&pipe_2), 0, sizeof(pipe_2));
		nimln_(3639, "system.nim");
		i_3 = ((NI) 0);
		nimln_(3640, "system.nim");
		T103_ = (pipes ? pipes->Sup.len : 0);
		L_3 = T103_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_2;
				NimStringDesc* T106_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_77;
				if (!(i_3 < L_3)) goto LA105;
				nimln_(3642, "system.nim");
				if ((NU)(i_3) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_2.Field0 = pipes->data[i_3].Field0;
				pipe_2.Field1 = pipes->data[i_3].Field1;
				pipe_2.Field2 = pipes->data[i_3].Field2;
				pipe_2.Field3 = pipes->data[i_3].Field3;
				nimln_(201, "pipeline.nim");
				component_2 = pipe_2.Field2;
				nimln_(204, "pipeline.nim");
				T106_ = (NimStringDesc*)0;
				T106_ = rawNewString(component_2->Sup.len + 14);
appendString(T106_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_75));
appendString(T106_, component_2);
appendString(T106_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_76));
				mainCode = resizeString(mainCode, T106_->Sup.len + 0);
appendString(mainCode, T106_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_77 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_77);
				nimln_(3644, "system.nim");
				{
					NI T109_;
					T109_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T109_ == L_3))) goto LA110_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA110_: ;
			} LA105: ;
		}
	}
	nimln_(207, "pipeline.nim");
	pipeIndex = ((NI) 0);
	{
		tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ pipe_3;
		NI i_4;
		NI L_4;
		NI T113_;
		memset((void*)(&pipe_3), 0, sizeof(pipe_3));
		nimln_(3639, "system.nim");
		i_4 = ((NI) 0);
		nimln_(3640, "system.nim");
		T113_ = (pipes ? pipes->Sup.len : 0);
		L_4 = T113_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_3;
				NimStringDesc* componentQueue;
				NimStringDesc* T116_;
				NimStringDesc* nextComponentQueue;
				NimStringDesc* T124_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_85;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_86;
				if (!(i_4 < L_4)) goto LA115;
				nimln_(3642, "system.nim");
				if ((NU)(i_4) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_3.Field0 = pipes->data[i_4].Field0;
				pipe_3.Field1 = pipes->data[i_4].Field1;
				pipe_3.Field2 = pipes->data[i_4].Field2;
				pipe_3.Field3 = pipes->data[i_4].Field3;
				nimln_(210, "pipeline.nim");
				if ((NU)(pipeIndex) >= (NU)(pipes->Sup.len)) raiseIndexError();
				component_3 = pipes->data[pipeIndex].Field2;
				nimln_(211, "pipeline.nim");
				T116_ = (NimStringDesc*)0;
				T116_ = rawNewString(component_3->Sup.len + 3);
appendString(T116_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_75));
appendString(T116_, component_3);
				componentQueue = T116_;
				nimln_(212, "pipeline.nim");
				{
					NI T119_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_78;
					NimStringDesc* T122_;
					NI TM_tTXdAEOT2QIDPKqCGS4wCw_79;
					T119_ = (pipes ? pipes->Sup.len : 0);
					TM_tTXdAEOT2QIDPKqCGS4wCw_78 = subInt(T119_, ((NI) 1));
					if (!(pipeIndex < (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_78))) goto LA120_;
					T122_ = (NimStringDesc*)0;
					TM_tTXdAEOT2QIDPKqCGS4wCw_79 = addInt(pipeIndex, ((NI) 1));
					if ((NU)((NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_79)) >= (NU)(pipes->Sup.len)) raiseIndexError();
					T122_ = rawNewString(pipes->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_79)].Field2->Sup.len + 3);
appendString(T122_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_75));
appendString(T122_, pipes->data[(NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_79)].Field2);
					nextComponentQueue = T122_;
				}
				goto LA117_;
				LA120_: ;
				{
					nextComponentQueue = copyString(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_80));
				}
				LA117_: ;
				nimln_(215, "pipeline.nim");
				T124_ = (NimStringDesc*)0;
				T124_ = rawNewString(component_3->Sup.len + component_3->Sup.len + componentQueue->Sup.len + nextComponentQueue->Sup.len + 43);
appendString(T124_, component_3);
appendString(T124_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_81));
appendString(T124_, component_3);
appendString(T124_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_82));
appendString(T124_, componentQueue);
appendString(T124_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_83));
appendString(T124_, nextComponentQueue);
appendString(T124_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_84));
				mainCode = resizeString(mainCode, T124_->Sup.len + 0);
appendString(mainCode, T124_);
				nimln_(218, "pipeline.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_85 = addInt(pipeIndex, ((NI) 1));
				pipeIndex = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_85);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_86 = addInt(i_4, ((NI) 1));
				i_4 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_86);
				nimln_(3644, "system.nim");
				{
					NI T127_;
					T127_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T127_ == L_4))) goto LA128_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA128_: ;
			} LA115: ;
		}
	}
	nimln_(221, "pipeline.nim");
	T130_ = (NimStringDesc*)0;
	if ((NU)(((NI) 0)) >= (NU)(pipes->Sup.len)) raiseIndexError();
	T130_ = rawNewString(generatorName->Sup.len + pipes->data[((NI) 0)].Field2->Sup.len + 18);
appendString(T130_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_87));
appendString(T130_, generatorName);
appendString(T130_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_88));
appendString(T130_, pipes->data[((NI) 0)].Field2);
appendString(T130_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_89));
	mainCode = resizeString(mainCode, T130_->Sup.len + 0);
appendString(mainCode, T130_);
	{
		tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ pipe_4;
		NI i_5;
		NI L_5;
		NI T132_;
		memset((void*)(&pipe_4), 0, sizeof(pipe_4));
		nimln_(3639, "system.nim");
		i_5 = ((NI) 0);
		nimln_(3640, "system.nim");
		T132_ = (pipes ? pipes->Sup.len : 0);
		L_5 = T132_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_4;
				NimStringDesc* T135_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_91;
				if (!(i_5 < L_5)) goto LA134;
				nimln_(3642, "system.nim");
				if ((NU)(i_5) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_4.Field0 = pipes->data[i_5].Field0;
				pipe_4.Field1 = pipes->data[i_5].Field1;
				pipe_4.Field2 = pipes->data[i_5].Field2;
				pipe_4.Field3 = pipes->data[i_5].Field3;
				nimln_(225, "pipeline.nim");
				component_4 = pipe_4.Field2;
				nimln_(228, "pipeline.nim");
				T135_ = (NimStringDesc*)0;
				T135_ = rawNewString(component_4->Sup.len + 17);
appendString(T135_, component_4);
appendString(T135_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_90));
				mainCode = resizeString(mainCode, T135_->Sup.len + 0);
appendString(mainCode, T135_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_91 = addInt(i_5, ((NI) 1));
				i_5 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_91);
				nimln_(3644, "system.nim");
				{
					NI T138_;
					T138_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T138_ == L_5))) goto LA139_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA139_: ;
			} LA134: ;
		}
	}
	{
		tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ pipe_5;
		NI i_6;
		NI L_6;
		NI T142_;
		memset((void*)(&pipe_5), 0, sizeof(pipe_5));
		nimln_(3639, "system.nim");
		i_6 = ((NI) 0);
		nimln_(3640, "system.nim");
		T142_ = (pipes ? pipes->Sup.len : 0);
		L_6 = T142_;
		{
			nimln_(3641, "system.nim");
			while (1) {
				NimStringDesc* component_5;
				NimStringDesc* T145_;
				NI TM_tTXdAEOT2QIDPKqCGS4wCw_93;
				if (!(i_6 < L_6)) goto LA144;
				nimln_(3642, "system.nim");
				if ((NU)(i_6) >= (NU)(pipes->Sup.len)) raiseIndexError();
				pipe_5.Field0 = pipes->data[i_6].Field0;
				pipe_5.Field1 = pipes->data[i_6].Field1;
				pipe_5.Field2 = pipes->data[i_6].Field2;
				pipe_5.Field3 = pipes->data[i_6].Field3;
				nimln_(232, "pipeline.nim");
				component_5 = pipe_5.Field2;
				nimln_(235, "pipeline.nim");
				T145_ = (NimStringDesc*)0;
				T145_ = rawNewString(component_5->Sup.len + 16);
appendString(T145_, component_5);
appendString(T145_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_92));
				mainCode = resizeString(mainCode, T145_->Sup.len + 0);
appendString(mainCode, T145_);
				nimln_(3643, "system.nim");
				TM_tTXdAEOT2QIDPKqCGS4wCw_93 = addInt(i_6, ((NI) 1));
				i_6 = (NI)(TM_tTXdAEOT2QIDPKqCGS4wCw_93);
				nimln_(3644, "system.nim");
				{
					NI T148_;
					T148_ = (pipes ? pipes->Sup.len : 0);
					if (!!((T148_ == L_6))) goto LA149_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_41));
				}
				LA149_: ;
			} LA144: ;
		}
	}
	nimln_(238, "pipeline.nim");
	code = resizeString(code, 27);
appendString(code, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_94));
	nimln_(239, "pipeline.nim");
	nsuRemoveSuffixString((&mainCode), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
	nimln_(240, "pipeline.nim");
	T151_ = (NimStringDesc*)0;
	T152_ = (NimStringDesc*)0;
	T152_ = nsuIndent(mainCode, ((NI) 1), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_71));
	T151_ = rawNewString(T152_->Sup.len + 1);
appendString(T151_, T152_);
appendString(T151_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_46));
	code = resizeString(code, T151_->Sup.len + 0);
appendString(code, T151_);
	nimln_(243, "pipeline.nim");
	result = copyString(code);
	nimln_(245, "pipeline.nim");
	{
		if (!NIM_FALSE) goto LA155_;
		nimln_(246, "pipeline.nim");
		printf("%s\012", code? (code)->data:"nil");
		fflush(stdout);
	}
	LA155_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, runFile_5CPntwlWIrrur0HQZuCUCg)(NimStringDesc* path) {
	NimStringDesc* code;
	NimStringDesc* T1_;
	NCSTRING T2_;
	NimStringDesc* T3_;
	NI T4_;
	tyObject_Slice_qL3WGViqT0p5sVr4YFHsLg T5_;
	NimStringDesc* T6_;
	NI result;
	nimfr_("runFile", "pipeline.nim");
	nimln_(252, "pipeline.nim");
	code = compile_yRlCrCBaVd6dlyekZPc32w(path);
	nimln_(255, "pipeline.nim");
	Dl_125184_();
	nimln_(258, "pipeline.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NCSTRING)0;
	T2_ = Dl_125943_();
	T3_ = (NimStringDesc*)0;
	T3_ = cstrToNimstr(T2_);
	T4_ = (NI)0;
	T4_ = rfind_GYN9aIPE4YImn9c3fuLInlTg(path, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_21), ((NI) -1));
	T5_ = dotdot__18yoMoUbfoITYgEZSwZDYAtimes(((NI) 0), T4_);
	T6_ = (NimStringDesc*)0;
	T6_ = X5BX5D__Sq9b57KCLKZryBwyHy49aBswsystem(path, T5_);
	T1_ = rawNewString(T3_->Sup.len + T6_->Sup.len + 1);
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_95));
appendString(T1_, T6_);
	Dl_125822_(T1_->data);
	nimln_(261, "pipeline.nim");
	result = Dl_125255_(code->data);
	nimln_(264, "pipeline.nim");
	Dl_125923_();
	popFrame();
}

N_NIMCALL(void, compileFile_5CPntwlWIrrur0HQZuCUCg_2)(NimStringDesc* path) {
	NimStringDesc* code;
	NimStringDesc* targetPath;
	nimfr_("compileFile", "pipeline.nim");
	nimln_(269, "pipeline.nim");
	code = compile_yRlCrCBaVd6dlyekZPc32w(path);
	nimln_(272, "pipeline.nim");
	targetPath = nsuReplaceStr(path, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_96), ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_97));
	nimln_(275, "pipeline.nim");
	writeFile_c1B29b0ZdDRPHc27YaKqwaA(targetPath, code);
	popFrame();
}

N_NIMCALL(void, main_QkzkYHgocTG2Pef9bzDB4lw)(void) {
	NI T1_;
	nimfr_("main", "pipeline.nim");
	nimln_(278, "pipeline.nim");
	T1_ = (NI)0;
	T1_ = paramCount_T74rCHY8RMV0X07YnKmggw();
	switch (T1_) {
	case ((NI) 0):
	{
		nimln_(281, "pipeline.nim");
		printf("%s\012", ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_98)? (((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_98))->data:"nil");
		fflush(stdout);
		nimln_(282, "pipeline.nim");
		printf("%s\012", ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_99)? (((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_99))->data:"nil");
		fflush(stdout);
	}
	break;
	case ((NI) 1):
	{
		NimStringDesc* path;
		nimln_(285, "pipeline.nim");
		path = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		nimln_(288, "pipeline.nim");
		runFile_5CPntwlWIrrur0HQZuCUCg(path);
	}
	break;
	case ((NI) 2):
	{
		NimStringDesc* T5_;
		nimln_(290, "pipeline.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_100))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_101))) goto LA6_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_102))) goto LA7_;
		if (eqStrings(T5_, ((NimStringDesc*) &TM_tTXdAEOT2QIDPKqCGS4wCw_103))) goto LA7_;
		goto LA8_;
		LA6_: ;
		{
			NimStringDesc* path_2;
			nimln_(293, "pipeline.nim");
			path_2 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			nimln_(296, "pipeline.nim");
			runFile_5CPntwlWIrrur0HQZuCUCg(path_2);
		}
		goto LA9_;
		LA7_: ;
		{
			NimStringDesc* path_3;
			nimln_(299, "pipeline.nim");
			path_3 = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
			nimln_(302, "pipeline.nim");
			compileFile_5CPntwlWIrrur0HQZuCUCg_2(path_3);
		}
		goto LA9_;
		LA8_: ;
		{
		}
		LA9_: ;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	python_pythonDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	pipelineDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	python_pythonInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("pipeline", "pipeline.nim");
	nimln_(306, "pipeline.nim");
	main_QkzkYHgocTG2Pef9bzDB4lw();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, pipelineDatInit000)(void) {
static TNimNode* TM_tTXdAEOT2QIDPKqCGS4wCw_2[2];
static TNimNode* TM_tTXdAEOT2QIDPKqCGS4wCw_6[4];
static TNimNode* TM_tTXdAEOT2QIDPKqCGS4wCw_7[2];
NI TM_tTXdAEOT2QIDPKqCGS4wCw_9;
static char* NIM_CONST TM_tTXdAEOT2QIDPKqCGS4wCw_8[2] = {
"pTransformer", 
"pFilter"};
static TNimNode TM_tTXdAEOT2QIDPKqCGS4wCw_0[11];
NTI_UV3llMMYFckfui8YMBuUZA_.size = sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA);
NTI_UV3llMMYFckfui8YMBuUZA_.kind = 18;
NTI_UV3llMMYFckfui8YMBuUZA_.base = 0;
NTI_UV3llMMYFckfui8YMBuUZA_.flags = 2;
TM_tTXdAEOT2QIDPKqCGS4wCw_2[0] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[1];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field0);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[1].name = "Field0";
TM_tTXdAEOT2QIDPKqCGS4wCw_2[1] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[2];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].offset = offsetof(tyTuple_UV3llMMYFckfui8YMBuUZA, Field1);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[2].name = "Field1";
TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].len = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].kind = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[0].sons = &TM_tTXdAEOT2QIDPKqCGS4wCw_2[0];
NTI_UV3llMMYFckfui8YMBuUZA_.node = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[0];
NTI_7T6SqU26Y9ca7z9bynTdnpZQ_.size = sizeof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ);
NTI_7T6SqU26Y9ca7z9bynTdnpZQ_.kind = 18;
NTI_7T6SqU26Y9ca7z9bynTdnpZQ_.base = 0;
NTI_7T6SqU26Y9ca7z9bynTdnpZQ_.flags = 2;
TM_tTXdAEOT2QIDPKqCGS4wCw_6[0] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[4];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[4].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[4].offset = offsetof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ, Field0);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[4].name = "Field0";
TM_tTXdAEOT2QIDPKqCGS4wCw_6[1] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[5];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[5].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[5].offset = offsetof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ, Field1);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[5].name = "Field1";
TM_tTXdAEOT2QIDPKqCGS4wCw_6[2] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[6];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[6].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[6].offset = offsetof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ, Field2);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[6].name = "Field2";
TM_tTXdAEOT2QIDPKqCGS4wCw_6[3] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[7];
NTI_7vo6pbCJWqzFxcwxAp9bfIA_.size = sizeof(tyEnum_Pipes_7vo6pbCJWqzFxcwxAp9bfIA);
NTI_7vo6pbCJWqzFxcwxAp9bfIA_.kind = 14;
NTI_7vo6pbCJWqzFxcwxAp9bfIA_.base = 0;
NTI_7vo6pbCJWqzFxcwxAp9bfIA_.flags = 3;
for (TM_tTXdAEOT2QIDPKqCGS4wCw_9 = 0; TM_tTXdAEOT2QIDPKqCGS4wCw_9 < 2; TM_tTXdAEOT2QIDPKqCGS4wCw_9++) {
TM_tTXdAEOT2QIDPKqCGS4wCw_0[TM_tTXdAEOT2QIDPKqCGS4wCw_9+8].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[TM_tTXdAEOT2QIDPKqCGS4wCw_9+8].offset = TM_tTXdAEOT2QIDPKqCGS4wCw_9;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[TM_tTXdAEOT2QIDPKqCGS4wCw_9+8].name = TM_tTXdAEOT2QIDPKqCGS4wCw_8[TM_tTXdAEOT2QIDPKqCGS4wCw_9];
TM_tTXdAEOT2QIDPKqCGS4wCw_7[TM_tTXdAEOT2QIDPKqCGS4wCw_9] = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[TM_tTXdAEOT2QIDPKqCGS4wCw_9+8];
}
TM_tTXdAEOT2QIDPKqCGS4wCw_0[10].len = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[10].kind = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[10].sons = &TM_tTXdAEOT2QIDPKqCGS4wCw_7[0];
NTI_7vo6pbCJWqzFxcwxAp9bfIA_.node = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[10];
TM_tTXdAEOT2QIDPKqCGS4wCw_0[7].kind = 1;
TM_tTXdAEOT2QIDPKqCGS4wCw_0[7].offset = offsetof(tyTuple_7T6SqU26Y9ca7z9bynTdnpZQ, Field3);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[7].typ = (&NTI_7vo6pbCJWqzFxcwxAp9bfIA_);
TM_tTXdAEOT2QIDPKqCGS4wCw_0[7].name = "Field3";
TM_tTXdAEOT2QIDPKqCGS4wCw_0[3].len = 4; TM_tTXdAEOT2QIDPKqCGS4wCw_0[3].kind = 2; TM_tTXdAEOT2QIDPKqCGS4wCw_0[3].sons = &TM_tTXdAEOT2QIDPKqCGS4wCw_6[0];
NTI_7T6SqU26Y9ca7z9bynTdnpZQ_.node = &TM_tTXdAEOT2QIDPKqCGS4wCw_0[3];
NTI_6DnSqKvIUhqSESkW5cxf1Q_.size = sizeof(tySequence_6DnSqKvIUhqSESkW5cxf1Q*);
NTI_6DnSqKvIUhqSESkW5cxf1Q_.kind = 24;
NTI_6DnSqKvIUhqSESkW5cxf1Q_.base = (&NTI_7T6SqU26Y9ca7z9bynTdnpZQ_);
NTI_6DnSqKvIUhqSESkW5cxf1Q_.flags = 2;
NTI_6DnSqKvIUhqSESkW5cxf1Q_.marker = Marker_tySequence_6DnSqKvIUhqSESkW5cxf1Q;
}

