/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/calebwin/Projects/pipeline/src/nimcache/python_python.o /home/calebwin/Projects/pipeline/src/nimcache/python_python.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ;
typedef struct tyObject_PyCodeObject_XSBNLHLvz1tbKA29aizinXg tyObject_PyCodeObject_XSBNLHLvz1tbKA29aizinXg;
typedef struct tyObject_Frozen_sbUKIyy9bYWqxJELyntudcA tyObject_Frozen_sbUKIyy9bYWqxJELyntudcA;
typedef struct tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA;
typedef struct tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct RootObj RootObj;
typedef struct tyObject_PyNumberMethods_LSR3XtVN0tFrJYe6o8gCgQ tyObject_PyNumberMethods_LSR3XtVN0tFrJYe6o8gCgQ;
typedef struct tyObject_PySequenceMethods_ddSkdGkyImNYbzy2w2aLlg tyObject_PySequenceMethods_ddSkdGkyImNYbzy2w2aLlg;
typedef struct tyObject_PyMappingMethods_rcLa4bLbfbL9bbP19cjtlh7w tyObject_PyMappingMethods_rcLa4bLbfbL9bbP19cjtlh7w;
typedef struct tyObject_PyBufferProcs_Nn9aWKCn7N6fh5PUyZcZtxQ tyObject_PyBufferProcs_Nn9aWKCn7N6fh5PUyZcZtxQ;
typedef struct tyObject_PyMethodDef_OBFefD8iTzzk9cdOODJXbmw tyObject_PyMethodDef_OBFefD8iTzzk9cdOODJXbmw;
typedef struct tyObject_PyMemberDef_RHhe9bgRCbWTkxTigk6WdVw tyObject_PyMemberDef_RHhe9bgRCbWTkxTigk6WdVw;
typedef struct tyObject_PyGetSetDef_YyAVBmDR7zNZzTUODNw79cw tyObject_PyGetSetDef_YyAVBmDR7zNZzTUODNw79cw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef N_CDECL_PTR(NI, tyProc_6fbF5Tmmbq9c7Wc9c4RmsEjA) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* args, NCSTRING format, ...);
typedef N_CDECL_PTR(NI, tyProc_c5M3OdNrug8OLWH2qDY4ug) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* args, NCSTRING format, void* x1, void* x2, void* x3, ...);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_OQFEhm9baJG49bpu1Gx9abXag) (NCSTRING format, ...);
typedef N_CDECL_PTR(NI, tyProc_EdjBuYYD7zEz4X9a9bJcx9c0A) (tyObject_PyCodeObject_XSBNLHLvz1tbKA29aizinXg* co, NI addrq);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NimStringDesc* tyArray_meGd17iD6izZVY5NTv9bHUA[10];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING path);
typedef N_CDECL_PTR(NI, tyProc_grsFbooLsFDKsgZemLk4tA) (NCSTRING str);
struct tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ {
NI obRefcnt;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* obType;
};
struct tyObject_PyCodeObject_XSBNLHLvz1tbKA29aizinXg {
  tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ Sup;
NI coArgcount;
NI coNlocals;
NI coStacksize;
NI coFlags;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coCode;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coConsts;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coNames;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coVarnames;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coFreevars;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coCellvars;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coFilename;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coName;
NI coFirstlineno;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* coLnotab;
};
struct tyObject_Frozen_sbUKIyy9bYWqxJELyntudcA {
NCSTRING name;
NI8* code;
NI size;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA {
  RootObj Sup;
NI32 obIval;
};
typedef N_CDECL_PTR(void, tyProc_KZzJ2W3JaZrexaZW7dVi3w) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob);
typedef N_CDECL_PTR(NI, tyProc_OHN9bcXqFngxkYn9bIXuKBTg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob, FILE* f, NI i);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_xZbL419b0lJundeQYdpEm9aQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NCSTRING name);
typedef N_CDECL_PTR(NI, tyProc_xEdPHZtJehp9a6ZeBcVW9aOA) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NCSTRING name, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2);
typedef N_CDECL_PTR(NI, tyProc_GBAXvfiH2FFIMA2FPSQRbg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_eMgIfGeKar3rL0wS3QKJOQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob);
typedef N_CDECL_PTR(NI32, tyProc_flfJ5z84PEq4E1YCVIWe9bw) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_0AtDg5iQ6BVNBWyDefkydg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob3);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_dViGUhTeGyI3ScP4oFnmuQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2);
typedef N_CDECL_PTR(NI, tyProc_WjTP9bidMT0qLxhzCAMICXQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob3);
typedef N_CDECL_PTR(NI, tyProc_kAE0MEgJ9cX6cSAyDwEhJWg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, void* p);
typedef N_CDECL_PTR(NI, tyProc_PIiQrLQ9brsd9cbPNq4hUc8w) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyProc_kAE0MEgJ9cX6cSAyDwEhJWg prc, void* p);
typedef N_CDECL_PTR(NI, tyProc_Z2C3zMjtk1DMeTGTUS7Bfw) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_H5xrxU09bhmDcEfxmAveWFw) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2, NI i);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_gBbQoS5FYsMeXwzB9bXlR6A) (tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* self, NI nitems);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_3YOtCGczpW8wpoH9bpfou9aw) (tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* subtype, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* args, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* kwds);
struct tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg {
  tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ Sup;
NI obSize;
NCSTRING tpName;
NI tpBasicsize;
NI tpItemsize;
tyProc_KZzJ2W3JaZrexaZW7dVi3w tpDealloc;
tyProc_OHN9bcXqFngxkYn9bIXuKBTg tpPrint;
tyProc_xZbL419b0lJundeQYdpEm9aQ tpGetattr;
tyProc_xEdPHZtJehp9a6ZeBcVW9aOA tpSetattr;
tyProc_GBAXvfiH2FFIMA2FPSQRbg tpCompare;
tyProc_eMgIfGeKar3rL0wS3QKJOQ tpRepr;
tyObject_PyNumberMethods_LSR3XtVN0tFrJYe6o8gCgQ* tpAsNumber;
tyObject_PySequenceMethods_ddSkdGkyImNYbzy2w2aLlg* tpAsSequence;
tyObject_PyMappingMethods_rcLa4bLbfbL9bbP19cjtlh7w* tpAsMapping;
tyProc_flfJ5z84PEq4E1YCVIWe9bw tpHash;
tyProc_0AtDg5iQ6BVNBWyDefkydg tpCall;
tyProc_eMgIfGeKar3rL0wS3QKJOQ tpStr;
tyProc_dViGUhTeGyI3ScP4oFnmuQ tpGetattro;
tyProc_WjTP9bidMT0qLxhzCAMICXQ tpSetattro;
tyObject_PyBufferProcs_Nn9aWKCn7N6fh5PUyZcZtxQ* tpAsBuffer;
NI32 tpFlags;
NCSTRING tpDoc;
tyProc_PIiQrLQ9brsd9cbPNq4hUc8w tpTraverse;
tyProc_Z2C3zMjtk1DMeTGTUS7Bfw tpClear;
tyProc_H5xrxU09bhmDcEfxmAveWFw tpRichcompare;
NI32 tpWeaklistoffset;
tyProc_eMgIfGeKar3rL0wS3QKJOQ tpIter;
tyProc_eMgIfGeKar3rL0wS3QKJOQ tpIternext;
tyObject_PyMethodDef_OBFefD8iTzzk9cdOODJXbmw* tpMethods;
tyObject_PyMemberDef_RHhe9bgRCbWTkxTigk6WdVw* tpMembers;
tyObject_PyGetSetDef_YyAVBmDR7zNZzTUODNw79cw* tpGetset;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* tpBase;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpDict;
tyProc_0AtDg5iQ6BVNBWyDefkydg tpDescrGet;
tyProc_WjTP9bidMT0qLxhzCAMICXQ tpDescrSet;
NI32 tpDictoffset;
tyProc_WjTP9bidMT0qLxhzCAMICXQ tpInit;
tyProc_gBbQoS5FYsMeXwzB9bXlR6A tpAlloc;
tyProc_3YOtCGczpW8wpoH9bpfou9aw tpNew;
tyProc_KZzJ2W3JaZrexaZW7dVi3w tpFree;
tyProc_Z2C3zMjtk1DMeTGTUS7Bfw tpIsGc;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpBases;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpMro;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpCache;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpSubclasses;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* tpWeaklist;
void* tpXxx7;
void* tpXxx8;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_CDECL_PTR(NI, tyProc_QuEFRlTQo9a9bPTw7r9b77nIw) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** ob1, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** ob2);
struct tyObject_PyNumberMethods_LSR3XtVN0tFrJYe6o8gCgQ {
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbAdd;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbSubstract;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbMultiply;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbDivide;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbRemainder;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbDivmod;
tyProc_0AtDg5iQ6BVNBWyDefkydg nbPower;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbNegative;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbPositive;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbAbsolute;
tyProc_Z2C3zMjtk1DMeTGTUS7Bfw nbNonzero;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbInvert;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbLshift;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbRshift;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbAnd;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbXor;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbOr;
tyProc_QuEFRlTQo9a9bPTw7r9b77nIw nbCoerce;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbInt;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbLong;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbFloat;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbOct;
tyProc_eMgIfGeKar3rL0wS3QKJOQ nbHex;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceAdd;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceSubtract;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceMultiply;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceDivide;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceRemainder;
tyProc_0AtDg5iQ6BVNBWyDefkydg nbInplacePower;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceLshift;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceRshift;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceAnd;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceXor;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceOr;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbFloorDivide;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbTrueDivide;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceFloorDivide;
tyProc_dViGUhTeGyI3ScP4oFnmuQ nbInplaceTrueDivide;
};
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_WWdSYDtjVcntW9bMAEaL9clQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i);
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_BZvNgdY2tCZHGSNhvd01hw) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i1, NI i2);
typedef N_CDECL_PTR(NI, tyProc_69cposdai2Tr6jDF8T1SXag) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2);
typedef N_CDECL_PTR(NI, tyProc_taPv5lSoLPJ1MZvseWEiYA) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i1, NI i2, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob2);
struct tyObject_PySequenceMethods_ddSkdGkyImNYbzy2w2aLlg {
tyProc_Z2C3zMjtk1DMeTGTUS7Bfw sqLength;
tyProc_dViGUhTeGyI3ScP4oFnmuQ sqConcat;
tyProc_WWdSYDtjVcntW9bMAEaL9clQ sqRepeat;
tyProc_WWdSYDtjVcntW9bMAEaL9clQ sqItem;
tyProc_BZvNgdY2tCZHGSNhvd01hw sqSlice;
tyProc_69cposdai2Tr6jDF8T1SXag sqAssItem;
tyProc_taPv5lSoLPJ1MZvseWEiYA sqAssSlice;
tyProc_GBAXvfiH2FFIMA2FPSQRbg sqContains;
tyProc_dViGUhTeGyI3ScP4oFnmuQ sqInplaceConcat;
tyProc_WWdSYDtjVcntW9bMAEaL9clQ sqInplaceRepeat;
};
struct tyObject_PyMappingMethods_rcLa4bLbfbL9bbP19cjtlh7w {
tyProc_Z2C3zMjtk1DMeTGTUS7Bfw mpLength;
tyProc_dViGUhTeGyI3ScP4oFnmuQ mpSubscript;
tyProc_WjTP9bidMT0qLxhzCAMICXQ mpAssSubscript;
};
typedef N_CDECL_PTR(NI, tyProc_fRUD0OFIqM64w3gQnlx9bWQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i, void* p);
typedef N_CDECL_PTR(NI, tyProc_ATxcHalW207gU9cTseCC9azQ) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i);
typedef N_CDECL_PTR(NI, tyProc_xsD9bk9cf9bTBq9bIMKNeVdKHg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ob1, NI i, NCSTRING pstr);
struct tyObject_PyBufferProcs_Nn9aWKCn7N6fh5PUyZcZtxQ {
tyProc_fRUD0OFIqM64w3gQnlx9bWQ bfGetreadbuffer;
tyProc_fRUD0OFIqM64w3gQnlx9bWQ bfGetwritebuffer;
tyProc_ATxcHalW207gU9cTseCC9azQ bfGetsegcount;
tyProc_xsD9bk9cf9bTBq9bIMKNeVdKHg bfGetcharbuffer;
};
struct tyObject_PyMethodDef_OBFefD8iTzzk9cdOODJXbmw {
NCSTRING mlName;
tyProc_dViGUhTeGyI3ScP4oFnmuQ mlMeth;
NI mlFlags;
NCSTRING mlDoc;
};
struct tyObject_PyMemberDef_RHhe9bgRCbWTkxTigk6WdVw {
NCSTRING name;
NI theType;
NI offset;
NI flags;
NCSTRING doc;
};
typedef N_CDECL_PTR(tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*, tyProc_afe66IstKrxHDw27rze4cA) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* obj, void* context);
typedef N_CDECL_PTR(NI, tyProc_osAO9cbvxk2zS3vUEpXfudg) (tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* obj, tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* value, void* context);
struct tyObject_PyGetSetDef_YyAVBmDR7zNZzTUODNw79cw {
NCSTRING name;
tyProc_afe66IstKrxHDw27rze4cA get;
tyProc_osAO9cbvxk2zS3vUEpXfudg Setter;
NCSTRING doc;
void* closure;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_IcbKISYSyVzVovtju1fygg_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, loadLib_EFK1MHQsQvQPg5NaJH389bA)(NimStringDesc* path, NIM_BOOL global_symbols);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, quit_y2WuTG82qH44FHhQsKXOCg)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
N_NIMCALL(void, init_WglEsuaErSQCpx9azEbIM9cw)(void* lib);
N_NIMCALL(void*, symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2)(void* lib, NCSTRING name);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
tyProc_6fbF5Tmmbq9c7Wc9c4RmsEjA PyArg_Parse_bJKflQwascImR9a9bnwrZ5NQ;
tyProc_c5M3OdNrug8OLWH2qDY4ug PyArg_ParseTuple_9akPF9apq7J5A9b2Z3Us8UdsA;
tyProc_OQFEhm9baJG49bpu1Gx9abXag Py_BuildValue_6ZycescJMjJVZbLN51sWsA;
tyProc_EdjBuYYD7zEz4X9a9bJcx9c0A PyCode_Addr2Line_bqoIw7BqB9bZFpHN9aZ0DCpQ;
tyProc_09bvyvHFtWbkzL5AHgf0bKw DLL_Py_GetBuildInfo_vIfZBpbgGRoHYNuChHDZtA;
NI* debugFlag_cipN4njzywC0aXq7fjrvTg;
NI* verboseFlag_z9byNTYXYpB6T9cNJWmLzkpg;
NI* interactiveFlag_6POkCA2Oj87Z34uaQpwN1A;
NI* optimizeFlag_q61vW1SAGY236cq0X4aFCw;
NI* noSiteFlag_v0ar9cFZth1Jfs2JmU9cH9cog;
NI* useClassExceptionsFlag_bn6jSu4ajw8xBgnYtdziLA;
NI* frozenFlag_7dHAiQYD8jaXVjQTyY2klg;
NI* tabcheckFlag_wlOx60ssvV4ZxoGRRoAndA;
NI* unicodeFlag_QowdpI2QeNtPzyPr8ydNnA;
NI* ignoreEnvironmentFlag_b6SI79cs8GoEkrGPAYggs3Q;
NI* divisionWarningFlag_NhQD9a9b1p4PbU3D1uaO76bw;
tyObject_Frozen_sbUKIyy9bYWqxJELyntudcA* importFrozenModules_UEJua1yq9c6OlpDQQyMFcsQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* noneVar_Pv9cQ9caRWg9aLHK3OZVcJrUw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* ellipsis_yIx0OLK1oEQnyGe9bMRKW6A;
tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA* falseVar_FM20wJSYVBHF4606h4qLzA;
tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA* trueVar_qcwIL9bV8DaEp7C31kjT9cww;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ* notImplemented_0QMZaC2AZ9apPS6RqZjaWUQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excAttributeError_Qqb5LInYhsRJDxJCLUgdQw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excEOFError_RnzMsmJJ0euMeKG8K89b9aLQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excIOError_Eh49ahP9cDb5IEGTSC4zDjgA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excImportError_9bW3wXG07m4bVhZVamxLWIg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excIndexError_RYLWpvIbDtGiDMgVjEkTwg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excKeyError_vsT7kR3RhstGUrLYEKxIMw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excKeyboardInterrupt_ikI8CDVkNF8sc6Xuidtniw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excMemoryError_wCF9cYDvUS6aFg4N06keslw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excNameError_0tnonxZmPbTr9avgf0Q6Y9bg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excOverflowError_JsNX6xhxvFo23PqWqVVQLA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excRuntimeError_oRZhloL2gsWZaBt1ZCMz1A;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excSyntaxError_S3KydVrB6uDvR81yOgmsBQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excSystemError_fNSEPUgPSrwY9akhJK6I4IQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excSystemExit_VEDbHqlzyRmaI53yodd0dQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excTypeError_cFJsJgrUZvlmuj4T9a8rRoQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excValueError_8mMQ9aN5guwmlX6X3uMpyMw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excZeroDivisionError_u1wND9a4o6BGItamEP9cWS1w;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excArithmeticError_STs9ayaRG5TYKZjwJgfa5Jw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excException_9b0zRWNXwxKhKIojU9a4tTKA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excFloatingPointError_Qsaaqxz83NuihP32uqG9bYw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excLookupError_zQYU3hYIZ5t5T3CAZXO1Vw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excStandardError_FOxgcBN1kun49aiuxorMpJw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excAssertionError_TQPHngaCu9aLfpCRRK4yBdA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excEnvironmentError_tn0Te0sgWWAQHiiOCNYycg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excIndentationError_CpcbYwwNZ0Mt5cv2GTgtMw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excMemoryErrorInst_9bpWwRhs9bophL5XpIundOig;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excNotImplementedError_9ach3nCtc1VhyffqwLm59cEA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excOSError_KJqy07IXBBpxoyxX0bIFpA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excTabError_t0QjRMyZJbKFjuPJSGUUTA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUnboundLocalError_kqSeQ1MTSCXqGsb6cylkEA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUnicodeError_2NV6ANevsigKlfVJ4c25yQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excWarning_gO9aw0iQLF2y0muRJ5V9a79aQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excDeprecationWarning_HuI9brUkHh0VOrntDqIm82Q;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excRuntimeWarning_R4v9cz5x9bVKQ9aFejA6maXQw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excSyntaxWarning_EPWUS19bZYKxXzYjxme0HvA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUserWarning_9akd5gruefoGh4iwlSVAqkA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excOverflowWarning_K8uo7P64YgDp6v21HvY2sg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excReferenceError_fUN15l9aOCjBQs4A7mi9aCTg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excStopIteration_1ziaPWqjNSB9cMklYKInBAQ;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excFutureWarning_YSSkYP9brCjVlV9a3bAdQEPA;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excPendingDeprecationWarning_Gc7lDuk9agJu6lsuJXq24Uw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUnicodeDecodeError_10dl7Yt8WNl0s3LZ9a8KbHg;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUnicodeEncodeError_dW6ij9bw4CWW2hai3FGkhMw;
tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ** excUnicodeTranslateError_QbJbReg7hqNwZkaQrHd8pw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* typeType_lqimq2fPdie3Pquzsmdjhg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* cfunctionType_cj02qAPMTHafAIIvjCuKTw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* cobjectType_0QLhRT2753MR9bIpa1FVIdw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* classType_imGd8AhixPaFO5jcRFw9a9bw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* codeType_nQEA4x4K9btzFnsWvNChy8Q;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* complexType_Lz9cpmM9cEgnAZPPKR8QT9bLA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* dictType_7XWjy9b4pfGCJu8esTkzdJA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* fileType_GjHyZAc7oo4hA23nPRm9bmg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* floatType_LxcJf9buYyOTiC0YCIRW59cA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* frameType_csVQO0Krz79by6K4FUWI0jA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* functionType_9caZJke9aBT9aPs4W5DDK5k3w;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* instanceType_Q64FHjXznoHzKcY0Gj9ceUQ;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* intType_IlvIZLpdWPC0EaMi9cmJJtw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* listType_jsGwDtymkzLx42xw60Yzgg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* longType_mvV63Rn9cNzLWBxnn8zZ3Rg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* methodType_arOKUWjmOqtDAhqsF4dXsQ;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* moduleType_q4IQYX3IVagjNUDQZloqWw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* objectType_uGPKiumgYi3XhdHR5Tkvbw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* rangeType_DHM09cEC19c9ahhKyfqSYKG6g;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* sliceType_KDv4JzCC9afoyQMGk8wgAcQ;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* stringType_9a6Am2OkwQNdNAdqcT49cTfQ;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* tupleType_kiJw9bdC9cnL19ac9brzUrD1mA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* baseobjectType_SWl28xzOEBYzTDH1oFHkpA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* bufferType_SM3elFrCwt1lbCnYmb6gAA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* calliterType_RLNKgguSmCRtE1N9cgg1ABA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* cellType_YHXcQTXKEOFR9bSkjWcRDFg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* classmethodType_Fr8cleNeF69bVyRvMfyYH0A;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* propertyType_7tBkeTmdCuUnLnDz5Zflng;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* seqiterType_yBFFfQFD9ckZK1nY1mtlWhA;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* staticmethodType_Y3iFD9cpTciw5MtY245BJlw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* superType_NxkZ6pxO4qbu5KQ9bVp8rNg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* symtableentryType_r5OBn2DyVVjIYo8yG2r44g;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* tracebackType_DcwBqaJ1zT7q6zQAUvLhQQ;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* unicodeType_vgcprU9aSvgh1rGrykL9cRqw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* wrapperdescrType_INFbOziSRvPY14zSJ7rwsg;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* basestringType_SfBqNKoYyscl8CxR850t8g;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* boolType_ajGxgKS5A9bbEiU2UQp19ajw;
tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg* enumType_t9cgj6719cSx0fOctLROeGVg;
void* lib_6RatyP7vXwn5cBx9bNFG9bng;
NimStringDesc* libName_ETlOG69cSNpnZuer7QcwqMQ;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
static void* TM_IcbKISYSyVzVovtju1fygg_15;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125184_;
tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_125822_;
tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_125943_;
tyProc_grsFbooLsFDKsgZemLk4tA Dl_125255_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_125923_;
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_3, "libpython2.7.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_4, "libpython2.6.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_5, "libpython2.5.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_6, "libpython2.4.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_7, "libpython2.3.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_8, "libpython2.2.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_9, "libpython2.1.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_10, "libpython2.0.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_11, "libpython1.6.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_12, "libpython1.5.so.1", 17);
NIM_CONST tyArray_meGd17iD6izZVY5NTv9bHUA LibNames_3XbpeWXr7zBWIulO4v9cXTw = {((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_3),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_4),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_5),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_6),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_7),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_8),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_9),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_10),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_11),
((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_12)}
;
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_14, "could not load python library", 29);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_17, "libpython2.7.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_19, "libpython2.6.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_21, "libpython2.5.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_23, "libpython2.4.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_25, "libpython2.3.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_27, "libpython2.2.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_29, "libpython2.1.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_31, "libpython2.0.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_33, "libpython1.6.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_35, "libpython1.5.so.1", 17);
STRING_LITERAL(TM_IcbKISYSyVzVovtju1fygg_36, "libpython(2.7|2.6|2.5|2.4|2.3|2.2|2.1|2.0|1.6|1.5).so.1", 55);
static N_NIMCALL(void, TM_IcbKISYSyVzVovtju1fygg_2)(void) {
	nimGCvisit((void*)libName_ETlOG69cSNpnZuer7QcwqMQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, init_WglEsuaErSQCpx9azEbIM9cw)(void* lib) {
	void* T1_;
	void* T2_;
	void* T3_;
	void* T4_;
	void* T5_;
	void* T6_;
	void* T7_;
	void* T8_;
	void* T9_;
	void* T10_;
	void* T11_;
	void* T12_;
	void* T13_;
	void* T14_;
	void* T15_;
	void* T16_;
	void* T17_;
	void* T18_;
	void* T19_;
	void* T20_;
	void* T21_;
	void* T22_;
	void* T23_;
	void* T24_;
	void* T25_;
	void* T26_;
	void* T27_;
	void* T28_;
	void* T29_;
	void* T30_;
	void* T31_;
	void* T32_;
	void* T33_;
	void* T34_;
	void* T35_;
	void* T36_;
	void* T37_;
	void* T38_;
	void* T39_;
	void* T40_;
	void* T41_;
	void* T42_;
	void* T43_;
	void* T44_;
	void* T45_;
	void* T46_;
	void* T47_;
	void* T48_;
	void* T49_;
	void* T50_;
	void* T51_;
	void* T52_;
	void* T53_;
	void* T54_;
	void* T55_;
	void* T56_;
	void* T57_;
	void* T58_;
	void* T59_;
	void* T60_;
	void* T61_;
	void* T62_;
	void* T63_;
	void* T64_;
	void* T65_;
	void* T66_;
	void* T67_;
	void* T68_;
	void* T69_;
	void* T70_;
	void* T71_;
	void* T72_;
	void* T73_;
	void* T74_;
	void* T75_;
	void* T76_;
	void* T77_;
	void* T78_;
	void* T79_;
	void* T80_;
	void* T81_;
	void* T82_;
	void* T83_;
	void* T84_;
	void* T85_;
	void* T86_;
	void* T87_;
	void* T88_;
	void* T89_;
	void* T90_;
	void* T91_;
	void* T92_;
	void* T93_;
	void* T94_;
	void* T95_;
	void* T96_;
	void* T97_;
	void* T98_;
	void* T99_;
	nimfr_("init", "python.nim");
	nimln_(2323, "python.nim");
	T1_ = (void*)0;
	T1_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_DebugFlag");
	debugFlag_cipN4njzywC0aXq7fjrvTg = ((NI*) (T1_));
	nimln_(2324, "python.nim");
	T2_ = (void*)0;
	T2_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_VerboseFlag");
	verboseFlag_z9byNTYXYpB6T9cNJWmLzkpg = ((NI*) (T2_));
	nimln_(2325, "python.nim");
	T3_ = (void*)0;
	T3_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_InteractiveFlag");
	interactiveFlag_6POkCA2Oj87Z34uaQpwN1A = ((NI*) (T3_));
	nimln_(2326, "python.nim");
	T4_ = (void*)0;
	T4_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_OptimizeFlag");
	optimizeFlag_q61vW1SAGY236cq0X4aFCw = ((NI*) (T4_));
	nimln_(2327, "python.nim");
	T5_ = (void*)0;
	T5_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_NoSiteFlag");
	noSiteFlag_v0ar9cFZth1Jfs2JmU9cH9cog = ((NI*) (T5_));
	nimln_(2328, "python.nim");
	nimln_(2329, "python.nim");
	T6_ = (void*)0;
	T6_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_UseClassExceptionsFlag");
	useClassExceptionsFlag_bn6jSu4ajw8xBgnYtdziLA = ((NI*) (T6_));
	nimln_(2331, "python.nim");
	T7_ = (void*)0;
	T7_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_FrozenFlag");
	frozenFlag_7dHAiQYD8jaXVjQTyY2klg = ((NI*) (T7_));
	nimln_(2332, "python.nim");
	T8_ = (void*)0;
	T8_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_TabcheckFlag");
	tabcheckFlag_wlOx60ssvV4ZxoGRRoAndA = ((NI*) (T8_));
	nimln_(2333, "python.nim");
	T9_ = (void*)0;
	T9_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_UnicodeFlag");
	unicodeFlag_QowdpI2QeNtPzyPr8ydNnA = ((NI*) (T9_));
	nimln_(2334, "python.nim");
	nimln_(2335, "python.nim");
	T10_ = (void*)0;
	T10_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_IgnoreEnvironmentFlag");
	ignoreEnvironmentFlag_b6SI79cs8GoEkrGPAYggs3Q = ((NI*) (T10_));
	nimln_(2337, "python.nim");
	T11_ = (void*)0;
	T11_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "Py_DivisionWarningFlag");
	divisionWarningFlag_NhQD9a9b1p4PbU3D1uaO76bw = ((NI*) (T11_));
	nimln_(2338, "python.nim");
	T12_ = (void*)0;
	T12_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "_Py_NoneStruct");
	noneVar_Pv9cQ9caRWg9aLHK3OZVcJrUw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*) (T12_));
	nimln_(2339, "python.nim");
	T13_ = (void*)0;
	T13_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "_Py_EllipsisObject");
	ellipsis_yIx0OLK1oEQnyGe9bMRKW6A = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*) (T13_));
	nimln_(2340, "python.nim");
	T14_ = (void*)0;
	T14_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "_Py_ZeroStruct");
	falseVar_FM20wJSYVBHF4606h4qLzA = ((tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA*) (T14_));
	nimln_(2341, "python.nim");
	T15_ = (void*)0;
	T15_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "_Py_TrueStruct");
	trueVar_qcwIL9bV8DaEp7C31kjT9cww = ((tyObject_PyIntObject_fTzY2QMDm4577IuaOef8LA*) (T15_));
	nimln_(2342, "python.nim");
	T16_ = (void*)0;
	T16_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "_Py_NotImplementedStruct");
	notImplemented_0QMZaC2AZ9apPS6RqZjaWUQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ*) (T16_));
	nimln_(2343, "python.nim");
	nimln_(2344, "python.nim");
	T17_ = (void*)0;
	T17_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyImport_FrozenModules");
	importFrozenModules_UEJua1yq9c6OlpDQQyMFcsQ = ((tyObject_Frozen_sbUKIyy9bYWqxJELyntudcA*) (T17_));
	nimln_(2346, "python.nim");
	nimln_(2347, "python.nim");
	T18_ = (void*)0;
	T18_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_AttributeError");
	excAttributeError_Qqb5LInYhsRJDxJCLUgdQw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T18_));
	nimln_(2349, "python.nim");
	T19_ = (void*)0;
	T19_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_EOFError");
	excEOFError_RnzMsmJJ0euMeKG8K89b9aLQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T19_));
	nimln_(2350, "python.nim");
	T20_ = (void*)0;
	T20_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_IOError");
	excIOError_Eh49ahP9cDb5IEGTSC4zDjgA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T20_));
	nimln_(2351, "python.nim");
	T21_ = (void*)0;
	T21_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_ImportError");
	excImportError_9bW3wXG07m4bVhZVamxLWIg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T21_));
	nimln_(2352, "python.nim");
	T22_ = (void*)0;
	T22_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_IndexError");
	excIndexError_RYLWpvIbDtGiDMgVjEkTwg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T22_));
	nimln_(2353, "python.nim");
	T23_ = (void*)0;
	T23_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_KeyError");
	excKeyError_vsT7kR3RhstGUrLYEKxIMw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T23_));
	nimln_(2354, "python.nim");
	nimln_(2355, "python.nim");
	T24_ = (void*)0;
	T24_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_KeyboardInterrupt");
	excKeyboardInterrupt_ikI8CDVkNF8sc6Xuidtniw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T24_));
	nimln_(2357, "python.nim");
	T25_ = (void*)0;
	T25_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_MemoryError");
	excMemoryError_wCF9cYDvUS6aFg4N06keslw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T25_));
	nimln_(2358, "python.nim");
	T26_ = (void*)0;
	T26_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_NameError");
	excNameError_0tnonxZmPbTr9avgf0Q6Y9bg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T26_));
	nimln_(2359, "python.nim");
	T27_ = (void*)0;
	T27_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_OverflowError");
	excOverflowError_JsNX6xhxvFo23PqWqVVQLA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T27_));
	nimln_(2360, "python.nim");
	T28_ = (void*)0;
	T28_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_RuntimeError");
	excRuntimeError_oRZhloL2gsWZaBt1ZCMz1A = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T28_));
	nimln_(2361, "python.nim");
	T29_ = (void*)0;
	T29_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_SyntaxError");
	excSyntaxError_S3KydVrB6uDvR81yOgmsBQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T29_));
	nimln_(2362, "python.nim");
	T30_ = (void*)0;
	T30_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_SystemError");
	excSystemError_fNSEPUgPSrwY9akhJK6I4IQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T30_));
	nimln_(2363, "python.nim");
	T31_ = (void*)0;
	T31_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_SystemExit");
	excSystemExit_VEDbHqlzyRmaI53yodd0dQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T31_));
	nimln_(2364, "python.nim");
	T32_ = (void*)0;
	T32_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_TypeError");
	excTypeError_cFJsJgrUZvlmuj4T9a8rRoQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T32_));
	nimln_(2365, "python.nim");
	T33_ = (void*)0;
	T33_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_ValueError");
	excValueError_8mMQ9aN5guwmlX6X3uMpyMw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T33_));
	nimln_(2366, "python.nim");
	nimln_(2367, "python.nim");
	T34_ = (void*)0;
	T34_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_ZeroDivisionError");
	excZeroDivisionError_u1wND9a4o6BGItamEP9cWS1w = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T34_));
	nimln_(2369, "python.nim");
	nimln_(2370, "python.nim");
	T35_ = (void*)0;
	T35_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_ArithmeticError");
	excArithmeticError_STs9ayaRG5TYKZjwJgfa5Jw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T35_));
	nimln_(2372, "python.nim");
	T36_ = (void*)0;
	T36_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_Exception");
	excException_9b0zRWNXwxKhKIojU9a4tTKA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T36_));
	nimln_(2373, "python.nim");
	nimln_(2374, "python.nim");
	T37_ = (void*)0;
	T37_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_FloatingPointError");
	excFloatingPointError_Qsaaqxz83NuihP32uqG9bYw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T37_));
	nimln_(2376, "python.nim");
	T38_ = (void*)0;
	T38_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_LookupError");
	excLookupError_zQYU3hYIZ5t5T3CAZXO1Vw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T38_));
	nimln_(2377, "python.nim");
	T39_ = (void*)0;
	T39_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_StandardError");
	excStandardError_FOxgcBN1kun49aiuxorMpJw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T39_));
	nimln_(2378, "python.nim");
	T40_ = (void*)0;
	T40_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_AssertionError");
	excAssertionError_TQPHngaCu9aLfpCRRK4yBdA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T40_));
	nimln_(2379, "python.nim");
	nimln_(2380, "python.nim");
	T41_ = (void*)0;
	T41_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_EnvironmentError");
	excEnvironmentError_tn0Te0sgWWAQHiiOCNYycg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T41_));
	nimln_(2382, "python.nim");
	nimln_(2383, "python.nim");
	T42_ = (void*)0;
	T42_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_IndentationError");
	excIndentationError_CpcbYwwNZ0Mt5cv2GTgtMw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T42_));
	nimln_(2385, "python.nim");
	nimln_(2386, "python.nim");
	T43_ = (void*)0;
	T43_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_MemoryErrorInst");
	excMemoryErrorInst_9bpWwRhs9bophL5XpIundOig = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T43_));
	nimln_(2388, "python.nim");
	nimln_(2389, "python.nim");
	T44_ = (void*)0;
	T44_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_NotImplementedError");
	excNotImplementedError_9ach3nCtc1VhyffqwLm59cEA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T44_));
	nimln_(2391, "python.nim");
	T45_ = (void*)0;
	T45_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_OSError");
	excOSError_KJqy07IXBBpxoyxX0bIFpA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T45_));
	nimln_(2392, "python.nim");
	T46_ = (void*)0;
	T46_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_TabError");
	excTabError_t0QjRMyZJbKFjuPJSGUUTA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T46_));
	nimln_(2393, "python.nim");
	nimln_(2394, "python.nim");
	T47_ = (void*)0;
	T47_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UnboundLocalError");
	excUnboundLocalError_kqSeQ1MTSCXqGsb6cylkEA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T47_));
	nimln_(2396, "python.nim");
	T48_ = (void*)0;
	T48_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UnicodeError");
	excUnicodeError_2NV6ANevsigKlfVJ4c25yQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T48_));
	nimln_(2397, "python.nim");
	T49_ = (void*)0;
	T49_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_Warning");
	excWarning_gO9aw0iQLF2y0muRJ5V9a79aQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T49_));
	nimln_(2398, "python.nim");
	nimln_(2399, "python.nim");
	T50_ = (void*)0;
	T50_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_DeprecationWarning");
	excDeprecationWarning_HuI9brUkHh0VOrntDqIm82Q = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T50_));
	nimln_(2401, "python.nim");
	nimln_(2402, "python.nim");
	T51_ = (void*)0;
	T51_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_RuntimeWarning");
	excRuntimeWarning_R4v9cz5x9bVKQ9aFejA6maXQw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T51_));
	nimln_(2404, "python.nim");
	T52_ = (void*)0;
	T52_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_SyntaxWarning");
	excSyntaxWarning_EPWUS19bZYKxXzYjxme0HvA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T52_));
	nimln_(2405, "python.nim");
	T53_ = (void*)0;
	T53_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UserWarning");
	excUserWarning_9akd5gruefoGh4iwlSVAqkA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T53_));
	nimln_(2406, "python.nim");
	nimln_(2407, "python.nim");
	T54_ = (void*)0;
	T54_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_OverflowWarning");
	excOverflowWarning_K8uo7P64YgDp6v21HvY2sg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T54_));
	nimln_(2409, "python.nim");
	nimln_(2410, "python.nim");
	T55_ = (void*)0;
	T55_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_ReferenceError");
	excReferenceError_fUN15l9aOCjBQs4A7mi9aCTg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T55_));
	nimln_(2412, "python.nim");
	T56_ = (void*)0;
	T56_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_StopIteration");
	excStopIteration_1ziaPWqjNSB9cMklYKInBAQ = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T56_));
	nimln_(2413, "python.nim");
	T57_ = (void*)0;
	T57_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_FutureWarning");
	excFutureWarning_YSSkYP9brCjVlV9a3bAdQEPA = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T57_));
	nimln_(2414, "python.nim");
	nimln_(2415, "python.nim");
	T58_ = (void*)0;
	T58_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_PendingDeprecationWarning");
	excPendingDeprecationWarning_Gc7lDuk9agJu6lsuJXq24Uw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T58_));
	nimln_(2417, "python.nim");
	nimln_(2418, "python.nim");
	T59_ = (void*)0;
	T59_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UnicodeDecodeError");
	excUnicodeDecodeError_10dl7Yt8WNl0s3LZ9a8KbHg = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T59_));
	nimln_(2420, "python.nim");
	nimln_(2421, "python.nim");
	T60_ = (void*)0;
	T60_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UnicodeEncodeError");
	excUnicodeEncodeError_dW6ij9bw4CWW2hai3FGkhMw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T60_));
	nimln_(2423, "python.nim");
	nimln_(2424, "python.nim");
	T61_ = (void*)0;
	T61_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyExc_UnicodeTranslateError");
	excUnicodeTranslateError_QbJbReg7hqNwZkaQrHd8pw = ((tyObject_PyObject_xdRGV0amF6jfWKzFy9aOOwQ**) (T61_));
	nimln_(2426, "python.nim");
	T62_ = (void*)0;
	T62_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyType_Type");
	typeType_lqimq2fPdie3Pquzsmdjhg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T62_));
	nimln_(2427, "python.nim");
	T63_ = (void*)0;
	T63_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyCFunction_Type");
	cfunctionType_cj02qAPMTHafAIIvjCuKTw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T63_));
	nimln_(2428, "python.nim");
	T64_ = (void*)0;
	T64_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyCObject_Type");
	cobjectType_0QLhRT2753MR9bIpa1FVIdw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T64_));
	nimln_(2429, "python.nim");
	T65_ = (void*)0;
	T65_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyClass_Type");
	classType_imGd8AhixPaFO5jcRFw9a9bw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T65_));
	nimln_(2430, "python.nim");
	T66_ = (void*)0;
	T66_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyCode_Type");
	codeType_nQEA4x4K9btzFnsWvNChy8Q = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T66_));
	nimln_(2431, "python.nim");
	T67_ = (void*)0;
	T67_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyComplex_Type");
	complexType_Lz9cpmM9cEgnAZPPKR8QT9bLA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T67_));
	nimln_(2432, "python.nim");
	T68_ = (void*)0;
	T68_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyDict_Type");
	dictType_7XWjy9b4pfGCJu8esTkzdJA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T68_));
	nimln_(2433, "python.nim");
	T69_ = (void*)0;
	T69_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyFile_Type");
	fileType_GjHyZAc7oo4hA23nPRm9bmg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T69_));
	nimln_(2434, "python.nim");
	T70_ = (void*)0;
	T70_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyFloat_Type");
	floatType_LxcJf9buYyOTiC0YCIRW59cA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T70_));
	nimln_(2435, "python.nim");
	T71_ = (void*)0;
	T71_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyFrame_Type");
	frameType_csVQO0Krz79by6K4FUWI0jA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T71_));
	nimln_(2436, "python.nim");
	T72_ = (void*)0;
	T72_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyFunction_Type");
	functionType_9caZJke9aBT9aPs4W5DDK5k3w = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T72_));
	nimln_(2437, "python.nim");
	T73_ = (void*)0;
	T73_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyInstance_Type");
	instanceType_Q64FHjXznoHzKcY0Gj9ceUQ = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T73_));
	nimln_(2438, "python.nim");
	T74_ = (void*)0;
	T74_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyInt_Type");
	intType_IlvIZLpdWPC0EaMi9cmJJtw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T74_));
	nimln_(2439, "python.nim");
	T75_ = (void*)0;
	T75_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyList_Type");
	listType_jsGwDtymkzLx42xw60Yzgg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T75_));
	nimln_(2440, "python.nim");
	T76_ = (void*)0;
	T76_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyLong_Type");
	longType_mvV63Rn9cNzLWBxnn8zZ3Rg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T76_));
	nimln_(2441, "python.nim");
	T77_ = (void*)0;
	T77_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyMethod_Type");
	methodType_arOKUWjmOqtDAhqsF4dXsQ = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T77_));
	nimln_(2442, "python.nim");
	T78_ = (void*)0;
	T78_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyModule_Type");
	moduleType_q4IQYX3IVagjNUDQZloqWw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T78_));
	nimln_(2443, "python.nim");
	T79_ = (void*)0;
	T79_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyObject_Type");
	objectType_uGPKiumgYi3XhdHR5Tkvbw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T79_));
	nimln_(2444, "python.nim");
	T80_ = (void*)0;
	T80_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyRange_Type");
	rangeType_DHM09cEC19c9ahhKyfqSYKG6g = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T80_));
	nimln_(2445, "python.nim");
	T81_ = (void*)0;
	T81_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PySlice_Type");
	sliceType_KDv4JzCC9afoyQMGk8wgAcQ = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T81_));
	nimln_(2446, "python.nim");
	T82_ = (void*)0;
	T82_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyString_Type");
	stringType_9a6Am2OkwQNdNAdqcT49cTfQ = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T82_));
	nimln_(2447, "python.nim");
	T83_ = (void*)0;
	T83_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyTuple_Type");
	tupleType_kiJw9bdC9cnL19ac9brzUrD1mA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T83_));
	nimln_(2448, "python.nim");
	T84_ = (void*)0;
	T84_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyUnicode_Type");
	unicodeType_vgcprU9aSvgh1rGrykL9cRqw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T84_));
	nimln_(2449, "python.nim");
	T85_ = (void*)0;
	T85_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyBaseObject_Type");
	baseobjectType_SWl28xzOEBYzTDH1oFHkpA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T85_));
	nimln_(2450, "python.nim");
	T86_ = (void*)0;
	T86_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyBuffer_Type");
	bufferType_SM3elFrCwt1lbCnYmb6gAA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T86_));
	nimln_(2451, "python.nim");
	T87_ = (void*)0;
	T87_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyCallIter_Type");
	calliterType_RLNKgguSmCRtE1N9cgg1ABA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T87_));
	nimln_(2452, "python.nim");
	T88_ = (void*)0;
	T88_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyCell_Type");
	cellType_YHXcQTXKEOFR9bSkjWcRDFg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T88_));
	nimln_(2453, "python.nim");
	T89_ = (void*)0;
	T89_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyClassMethod_Type");
	classmethodType_Fr8cleNeF69bVyRvMfyYH0A = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T89_));
	nimln_(2454, "python.nim");
	T90_ = (void*)0;
	T90_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyProperty_Type");
	propertyType_7tBkeTmdCuUnLnDz5Zflng = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T90_));
	nimln_(2455, "python.nim");
	T91_ = (void*)0;
	T91_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PySeqIter_Type");
	seqiterType_yBFFfQFD9ckZK1nY1mtlWhA = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T91_));
	nimln_(2456, "python.nim");
	nimln_(2457, "python.nim");
	T92_ = (void*)0;
	T92_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyStaticMethod_Type");
	staticmethodType_Y3iFD9cpTciw5MtY245BJlw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T92_));
	nimln_(2459, "python.nim");
	T93_ = (void*)0;
	T93_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PySuper_Type");
	superType_NxkZ6pxO4qbu5KQ9bVp8rNg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T93_));
	nimln_(2460, "python.nim");
	nimln_(2461, "python.nim");
	T94_ = (void*)0;
	T94_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PySymtableEntry_Type");
	symtableentryType_r5OBn2DyVVjIYo8yG2r44g = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T94_));
	nimln_(2463, "python.nim");
	T95_ = (void*)0;
	T95_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyTraceBack_Type");
	tracebackType_DcwBqaJ1zT7q6zQAUvLhQQ = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T95_));
	nimln_(2464, "python.nim");
	nimln_(2465, "python.nim");
	T96_ = (void*)0;
	T96_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyWrapperDescr_Type");
	wrapperdescrType_INFbOziSRvPY14zSJ7rwsg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T96_));
	nimln_(2467, "python.nim");
	T97_ = (void*)0;
	T97_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyBaseString_Type");
	basestringType_SfBqNKoYyscl8CxR850t8g = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T97_));
	nimln_(2468, "python.nim");
	T98_ = (void*)0;
	T98_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyBool_Type");
	boolType_ajGxgKS5A9bbEiU2UQp19ajw = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T98_));
	nimln_(2469, "python.nim");
	T99_ = (void*)0;
	T99_ = symAddr_fM7lTRTvv9a9axreJA2Bx7jA_2(lib, "PyEnum_Type");
	enumType_t9cgj6719cSx0fOctLROeGVg = ((tyObject_PyTypeObject_uU7FRB80Gw59aDf3xVF9cmGg*) (T99_));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, python_pythonInit000)(void) {
	nimfr_("python", "python.nim");
nimRegisterGlobalMarker(TM_IcbKISYSyVzVovtju1fygg_2);
	{
		NI i;
		nimln_(2092, "system.nim");
		i = ((NI) 0);
		nimln_(2093, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 9))) goto LA4_;
			{
				nimln_(2094, "system.nim");
				while (1) {
					NimStringDesc* T8_;
					NI TM_IcbKISYSyVzVovtju1fygg_13;
					nimln_(2095, "system.nim");
					T8_ = (NimStringDesc*)0;
					T8_ = libName_ETlOG69cSNpnZuer7QcwqMQ; libName_ETlOG69cSNpnZuer7QcwqMQ = copyStringRC1(LibNames_3XbpeWXr7zBWIulO4v9cXTw[(i)- 0]);
					if (T8_) nimGCunrefNoCycle(T8_);
					nimln_(2505, "python.nim");
					lib_6RatyP7vXwn5cBx9bNFG9bng = loadLib_EFK1MHQsQvQPg5NaJH389bA(libName_ETlOG69cSNpnZuer7QcwqMQ, NIM_TRUE);
					nimln_(2506, "python.nim");
					{
						nimln_(378, "system.nim");
						nimln_(2506, "python.nim");
						if (!!((lib_6RatyP7vXwn5cBx9bNFG9bng == NIM_NIL))) goto LA11_;
						nimln_(2508, "python.nim");
						goto LA1;
					}
					LA11_: ;
					nimln_(2096, "system.nim");
					{
						if (!(((NI) 9) <= ((NI) (i)))) goto LA15_;
						goto LA6;
					}
					LA15_: ;
					nimln_(2097, "system.nim");
					TM_IcbKISYSyVzVovtju1fygg_13 = addInt(i, ((NI) 1));
					if (TM_IcbKISYSyVzVovtju1fygg_13 < 0 || TM_IcbKISYSyVzVovtju1fygg_13 > 9) raiseOverflow();
					i = (NI)(TM_IcbKISYSyVzVovtju1fygg_13);
				}
			} LA6: ;
		}
		LA4_: ;
	} LA1: ;
	nimln_(2510, "python.nim");
	{
		if (!(lib_6RatyP7vXwn5cBx9bNFG9bng == NIM_NIL)) goto LA19_;
		nimln_(2511, "python.nim");
		quit_y2WuTG82qH44FHhQsKXOCg(((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_14), ((NI) 1));
	}
	LA19_: ;
	nimln_(2512, "python.nim");
	init_WglEsuaErSQCpx9azEbIM9cw(lib_6RatyP7vXwn5cBx9bNFG9bng);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, python_pythonDatInit000)(void) {
if (!((TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_17))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_19))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_21))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_23))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_25))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_27))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_29))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_31))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_33))
||(TM_IcbKISYSyVzVovtju1fygg_15 = nimLoadLibrary((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_35))
)) nimLoadLibraryError((NimStringDesc*) &TM_IcbKISYSyVzVovtju1fygg_36);
	Dl_125184_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_IcbKISYSyVzVovtju1fygg_15, "Py_Initialize");
	Dl_125822_ = (tyProc_5cp59bim9aJ4WupX5aVaD1Sg) nimGetProcAddr(TM_IcbKISYSyVzVovtju1fygg_15, "PySys_SetPath");
	Dl_125943_ = (tyProc_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_IcbKISYSyVzVovtju1fygg_15, "Py_GetPath");
	Dl_125255_ = (tyProc_grsFbooLsFDKsgZemLk4tA) nimGetProcAddr(TM_IcbKISYSyVzVovtju1fygg_15, "PyRun_SimpleString");
	Dl_125923_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_IcbKISYSyVzVovtju1fygg_15, "Py_Finalize");
}

